/*
###############################################################
#  Generated by:      Cadence Innovus 21.17-s075_1
#  OS:                Linux x86_64(Host ID 5013-w38)
#  Generated on:      Wed Mar 12 15:46:41 2025
#  Design:            polynomial_top
#  Command:           saveNetlist polynomial_top.v
###############################################################
*/
module polynomial_a3_b2_c9_d1_in_bits6_out_bits24_DW02_mult_2 (
	\A<5> , 
	\A<4> , 
	\A<3> , 
	\A<2> , 
	\A<1> , 
	\A<0> , 
	\B<5> , 
	\B<4> , 
	\B<3> , 
	\B<2> , 
	\B<1> , 
	\B<0> , 
	TC, 
	\PRODUCT<11> , 
	\PRODUCT<10> , 
	\PRODUCT<9> , 
	\PRODUCT<8> , 
	\PRODUCT<7> , 
	\PRODUCT<6> , 
	\PRODUCT<5> , 
	\PRODUCT<4> , 
	\PRODUCT<3> , 
	\PRODUCT<2> , 
	\PRODUCT<1> , 
	\PRODUCT<0> , 
	p1, 
	p2);
   input \A<5> ;
   input \A<4> ;
   input \A<3> ;
   input \A<2> ;
   input \A<1> ;
   input \A<0> ;
   input \B<5> ;
   input \B<4> ;
   input \B<3> ;
   input \B<2> ;
   input \B<1> ;
   input \B<0> ;
   input TC;
   output \PRODUCT<11> ;
   output \PRODUCT<10> ;
   output \PRODUCT<9> ;
   output \PRODUCT<8> ;
   output \PRODUCT<7> ;
   output \PRODUCT<6> ;
   output \PRODUCT<5> ;
   output \PRODUCT<4> ;
   output \PRODUCT<3> ;
   output \PRODUCT<2> ;
   output \PRODUCT<1> ;
   output \PRODUCT<0> ;
   output p1;
   input p2;

   // Internal wires
   wire \ab<5][3> ;
   wire \ab<5][0> ;
   wire \ab<4][5> ;
   wire \ab<4][3> ;
   wire \ab<4][2> ;
   wire \ab<4][1> ;
   wire \ab<4][0> ;
   wire \ab<3][5> ;
   wire \ab<3][4> ;
   wire \ab<3][2> ;
   wire \ab<3][1> ;
   wire \ab<3][0> ;
   wire \ab<2][5> ;
   wire \ab<2][4> ;
   wire \ab<2][3> ;
   wire \ab<2][1> ;
   wire \ab<2][0> ;
   wire \ab<1][5> ;
   wire \ab<1][4> ;
   wire \ab<1][3> ;
   wire \ab<1][2> ;
   wire \ab<1][0> ;
   wire \ab<0][5> ;
   wire \ab<0][4> ;
   wire \ab<0][3> ;
   wire \ab<0][2> ;
   wire \ab<0][1> ;
   wire \CARRYB<5][4> ;
   wire \CARRYB<5][3> ;
   wire \CARRYB<5][2> ;
   wire \CARRYB<5][1> ;
   wire \CARRYB<5][0> ;
   wire \CARRYB<4][4> ;
   wire \CARRYB<4][3> ;
   wire \CARRYB<4][2> ;
   wire \CARRYB<4][1> ;
   wire \CARRYB<4][0> ;
   wire \CARRYB<3][4> ;
   wire \CARRYB<3][3> ;
   wire \CARRYB<3][2> ;
   wire \CARRYB<3][1> ;
   wire \CARRYB<3][0> ;
   wire \CARRYB<2][4> ;
   wire \CARRYB<2][3> ;
   wire \CARRYB<2][2> ;
   wire \CARRYB<2][1> ;
   wire \CARRYB<2][0> ;
   wire \CARRYB<1][4> ;
   wire \CARRYB<1][3> ;
   wire \CARRYB<1][2> ;
   wire \CARRYB<1][1> ;
   wire \CARRYB<1][0> ;
   wire \SUMB<5][4> ;
   wire \SUMB<5][3> ;
   wire \SUMB<5][2> ;
   wire \SUMB<5][1> ;
   wire \SUMB<4][4> ;
   wire \SUMB<4][3> ;
   wire \SUMB<4][2> ;
   wire \SUMB<4][1> ;
   wire \SUMB<3][4> ;
   wire \SUMB<3][3> ;
   wire \SUMB<3][2> ;
   wire \SUMB<3][1> ;
   wire \SUMB<2][4> ;
   wire \SUMB<2][3> ;
   wire \SUMB<2][2> ;
   wire \SUMB<2][1> ;
   wire \SUMB<1][4> ;
   wire \SUMB<1][3> ;
   wire \SUMB<1][2> ;
   wire \SUMB<1][1> ;
   wire \A1<8> ;
   wire \A1<7> ;
   wire \A1<6> ;
   wire \A1<5> ;
   wire \A2<9> ;
   wire \A2<8> ;
   wire \A2<7> ;
   wire \A2<6> ;
   wire \A2<5> ;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;

   assign \PRODUCT<0>  = \B<0>  ;

   ADDFX1 S2_2_2 (.CO(\CARRYB<2][2> ),
	.S(\SUMB<2][2> ),
	.A(\B<2> ),
	.B(\CARRYB<1][2> ),
	.CI(\SUMB<1][3> ));
   ADDFX1 S2_3_3 (.CO(\CARRYB<3][3> ),
	.S(\SUMB<3][3> ),
	.A(\B<3> ),
	.B(\CARRYB<2][3> ),
	.CI(\SUMB<2][4> ));
   ADDFX1 S3_4_4 (.CO(\CARRYB<4][4> ),
	.S(\SUMB<4][4> ),
	.A(\B<4> ),
	.B(\CARRYB<3][4> ),
	.CI(\ab<3][5> ));
   ADDFX1 S1_2_0 (.CO(\CARRYB<2][0> ),
	.S(\PRODUCT<2> ),
	.A(\ab<2][0> ),
	.B(\CARRYB<1][0> ),
	.CI(\SUMB<1][1> ));
   ADDFX1 S5_4 (.CO(\CARRYB<5][4> ),
	.S(\SUMB<5][4> ),
	.A(\ab<4][5> ),
	.B(\CARRYB<4][4> ),
	.CI(\ab<4][5> ));
   ADDFX1 S2_2_1 (.CO(\CARRYB<2][1> ),
	.S(\SUMB<2][1> ),
	.A(\ab<2][1> ),
	.B(\CARRYB<1][1> ),
	.CI(\SUMB<1][2> ));
   ADDFX1 S2_4_3 (.CO(\CARRYB<4][3> ),
	.S(\SUMB<4][3> ),
	.A(\ab<4][3> ),
	.B(\CARRYB<3][3> ),
	.CI(\SUMB<3][4> ));
   ADDFX1 S2_4_2 (.CO(\CARRYB<4][2> ),
	.S(\SUMB<4][2> ),
	.A(\ab<4][2> ),
	.B(\CARRYB<3][2> ),
	.CI(\SUMB<3][3> ));
   ADDFX1 S2_4_1 (.CO(\CARRYB<4][1> ),
	.S(\SUMB<4][1> ),
	.A(\ab<4][1> ),
	.B(\CARRYB<3][1> ),
	.CI(\SUMB<3][2> ));
   ADDFX1 S2_3_2 (.CO(\CARRYB<3][2> ),
	.S(\SUMB<3][2> ),
	.A(\ab<3][2> ),
	.B(\CARRYB<2][2> ),
	.CI(\SUMB<2][3> ));
   ADDFX1 S3_3_4 (.CO(\CARRYB<3][4> ),
	.S(\SUMB<3][4> ),
	.A(\ab<3][4> ),
	.B(\CARRYB<2][4> ),
	.CI(\ab<2][5> ));
   ADDFX1 S3_2_4 (.CO(\CARRYB<2][4> ),
	.S(\SUMB<2][4> ),
	.A(\ab<2][4> ),
	.B(\CARRYB<1][4> ),
	.CI(\ab<1][5> ));
   ADDFX1 S2_2_3 (.CO(\CARRYB<2][3> ),
	.S(\SUMB<2][3> ),
	.A(\ab<2][3> ),
	.B(\CARRYB<1][3> ),
	.CI(\SUMB<1][4> ));
   ADDFX1 S1_3_0 (.CO(\CARRYB<3][0> ),
	.S(\PRODUCT<3> ),
	.A(\ab<3][0> ),
	.B(\CARRYB<2][0> ),
	.CI(\SUMB<2][1> ));
   ADDFX1 S2_3_1 (.CO(\CARRYB<3][1> ),
	.S(\SUMB<3][1> ),
	.A(\ab<3][1> ),
	.B(\CARRYB<2][1> ),
	.CI(\SUMB<2][2> ));
   ADDFX1 S4_1 (.CO(\CARRYB<5][1> ),
	.S(\SUMB<5][1> ),
	.A(\ab<1][5> ),
	.B(\CARRYB<4][1> ),
	.CI(\SUMB<4][2> ));
   ADDFX1 S4_3 (.CO(\CARRYB<5][3> ),
	.S(\SUMB<5][3> ),
	.A(\ab<5][3> ),
	.B(\CARRYB<4][3> ),
	.CI(\SUMB<4][4> ));
   ADDFX1 S4_2 (.CO(\CARRYB<5][2> ),
	.S(\SUMB<5][2> ),
	.A(\ab<2][5> ),
	.B(\CARRYB<4][2> ),
	.CI(\SUMB<4][3> ));
   ADDFX1 S4_0 (.CO(\CARRYB<5][0> ),
	.S(\PRODUCT<5> ),
	.A(\ab<5][0> ),
	.B(\CARRYB<4][0> ),
	.CI(\SUMB<4][1> ));
   ADDFX1 S1_4_0 (.CO(\CARRYB<4][0> ),
	.S(\PRODUCT<4> ),
	.A(\ab<4][0> ),
	.B(\CARRYB<3][0> ),
	.CI(\SUMB<3][1> ));
   INVX1 U2 (.Y(n27),
	.A(n15));
   INVX1 U3 (.Y(n26),
	.A(n12));
   CLKXOR2X1 U4 (.Y(\PRODUCT<1> ),
	.A(\ab<1][0> ),
	.B(\ab<0][1> ));
   CLKXOR2X1 U5 (.Y(\PRODUCT<6> ),
	.A(\CARRYB<5][0> ),
	.B(\SUMB<5][1> ));
   INVX1 U6 (.Y(n9),
	.A(\ab<0][4> ));
   INVX1 U7 (.Y(n7),
	.A(\ab<0][3> ));
   INVX1 U8 (.Y(n5),
	.A(\ab<0][2> ));
   INVX1 U9 (.Y(n4),
	.A(\ab<0][1> ));
   INVX1 U10 (.Y(n11),
	.A(\ab<0][5> ));
   INVX1 U11 (.Y(n8),
	.A(\ab<1][3> ));
   INVX1 U12 (.Y(n3),
	.A(\ab<1][0> ));
   INVX1 U13 (.Y(n10),
	.A(\ab<1][4> ));
   CLKXOR2X1 U14 (.Y(\A1<5> ),
	.A(\CARRYB<5][1> ),
	.B(\SUMB<5][2> ));
   CLKXOR2X1 U15 (.Y(\A1<7> ),
	.A(\CARRYB<5][3> ),
	.B(\SUMB<5][4> ));
   CLKXOR2X1 U16 (.Y(\A1<6> ),
	.A(\CARRYB<5][2> ),
	.B(\SUMB<5][3> ));
   AND2X1 U17 (.Y(\A2<7> ),
	.A(\SUMB<5][3> ),
	.B(\CARRYB<5][2> ));
   AND2X1 U18 (.Y(\A2<5> ),
	.A(\CARRYB<5][0> ),
	.B(\SUMB<5][1> ));
   AND2X1 U19 (.Y(\A2<6> ),
	.A(\SUMB<5][2> ),
	.B(\CARRYB<5][1> ));
   INVX1 U20 (.Y(n2),
	.A(\CARRYB<5][4> ));
   AND2X1 U21 (.Y(\A2<8> ),
	.A(\SUMB<5][4> ),
	.B(\CARRYB<5][3> ));
   CLKXOR2X1 U22 (.Y(\PRODUCT<11> ),
	.A(n25),
	.B(\A2<9> ));
   NOR2X1 U23 (.Y(\A2<9> ),
	.A(n28),
	.B(n2));
   NOR2X1 U24 (.Y(\CARRYB<1][3> ),
	.A(n8),
	.B(n9));
   CLKXOR2X1 U25 (.Y(\SUMB<1][4> ),
	.A(\ab<1][4> ),
	.B(\ab<0][5> ));
   NOR2X1 U26 (.Y(\CARRYB<1][4> ),
	.A(n10),
	.B(n11));
   NOR2X1 U27 (.Y(\CARRYB<1][1> ),
	.A(n32),
	.B(n5));
   CLKXOR2X1 U28 (.Y(\SUMB<1][2> ),
	.A(\ab<1][2> ),
	.B(\ab<0][3> ));
   NOR2X1 U29 (.Y(\CARRYB<1][0> ),
	.A(n3),
	.B(n4));
   CLKXOR2X1 U30 (.Y(\SUMB<1][1> ),
	.A(\B<1> ),
	.B(\ab<0][2> ));
   NOR2X1 U31 (.Y(\CARRYB<1][2> ),
	.A(n6),
	.B(n7));
   CLKXOR2X1 U32 (.Y(\SUMB<1][3> ),
	.A(\ab<1][3> ),
	.B(\ab<0][4> ));
   INVX1 U33 (.Y(n6),
	.A(\ab<1][2> ));
   INVX1 U35 (.Y(n28),
	.A(\B<5> ));
   INVX1 U36 (.Y(n32),
	.A(\B<1> ));
   INVX1 U37 (.Y(n31),
	.A(\B<2> ));
   INVX1 U38 (.Y(n29),
	.A(\B<4> ));
   INVX1 U39 (.Y(n30),
	.A(\B<3> ));
   CLKXOR2X1 U40 (.Y(\A1<8> ),
	.A(\CARRYB<5][4> ),
	.B(\B<5> ));
   NAND2X1 U41 (.Y(n12),
	.A(\A2<5> ),
	.B(\A1<5> ));
   NOR2X1 U42 (.Y(n13),
	.A(\A2<5> ),
	.B(\A1<5> ));
   NOR2BX1 U43 (.Y(\PRODUCT<7> ),
	.AN(n12),
	.B(n13));
   OR2X1 U44 (.Y(n16),
	.A(\A2<6> ),
	.B(\A1<6> ));
   NAND2X1 U45 (.Y(n15),
	.A(\A2<6> ),
	.B(\A1<6> ));
   NAND2X1 U46 (.Y(n14),
	.A(n16),
	.B(n15));
   XNOR2X1 U47 (.Y(\PRODUCT<8> ),
	.A(n26),
	.B(n14));
   AOI21X1 U48 (.Y(n19),
	.A0(n16),
	.A1(n26),
	.B0(n27));
   NAND2X1 U49 (.Y(n18),
	.A(\A2<7> ),
	.B(\A1<7> ));
   NOR2X1 U50 (.Y(n20),
	.A(\A2<7> ),
	.B(\A1<7> ));
   NOR2BX1 U51 (.Y(n17),
	.AN(n18),
	.B(n20));
   XNOR2X1 U52 (.Y(\PRODUCT<9> ),
	.A(n19),
	.B(n17));
   OAI21X1 U53 (.Y(n23),
	.A0(n20),
	.A1(n19),
	.B0(n18));
   OR2X1 U54 (.Y(n24),
	.A(\A2<8> ),
	.B(\A1<8> ));
   NAND2X1 U55 (.Y(n22),
	.A(\A2<8> ),
	.B(\A1<8> ));
   NAND2X1 U56 (.Y(n21),
	.A(n24),
	.B(n22));
   XNOR2X1 U57 (.Y(\PRODUCT<10> ),
	.A(n23),
	.B(n21));
   OAI2BB1X1 U58 (.Y(n25),
	.A0N(n24),
	.A1N(n23),
	.B0(n22));
   NOR2X1 U60 (.Y(\ab<5][3> ),
	.A(n28),
	.B(n30));
   NOR2X1 U63 (.Y(\ab<5][0> ),
	.A(n28),
	.B(p2));
   NOR2X1 U64 (.Y(\ab<4][5> ),
	.A(n28),
	.B(n29));
   NOR2X1 U65 (.Y(\ab<4][3> ),
	.A(n30),
	.B(n29));
   NOR2X1 U66 (.Y(\ab<4][2> ),
	.A(n31),
	.B(n29));
   NOR2X1 U67 (.Y(\ab<4][1> ),
	.A(n32),
	.B(n29));
   NOR2X1 U68 (.Y(\ab<4][0> ),
	.A(p2),
	.B(n29));
   NOR2X1 U69 (.Y(\ab<3][5> ),
	.A(n28),
	.B(n30));
   NOR2X1 U70 (.Y(\ab<3][4> ),
	.A(n29),
	.B(n30));
   NOR2X1 U71 (.Y(\ab<3][2> ),
	.A(n31),
	.B(n30));
   NOR2X1 U72 (.Y(\ab<3][1> ),
	.A(n32),
	.B(n30));
   NOR2X1 U73 (.Y(\ab<3][0> ),
	.A(p2),
	.B(n30));
   NOR2X1 U74 (.Y(\ab<2][5> ),
	.A(n28),
	.B(n31));
   NOR2X1 U75 (.Y(\ab<2][4> ),
	.A(n29),
	.B(n31));
   NOR2X1 U76 (.Y(\ab<2][3> ),
	.A(n30),
	.B(n31));
   NOR2X1 U77 (.Y(\ab<2][1> ),
	.A(n32),
	.B(n31));
   NOR2X1 U78 (.Y(\ab<2][0> ),
	.A(p2),
	.B(n31));
   NOR2X1 U79 (.Y(\ab<1][5> ),
	.A(n28),
	.B(n32));
   NOR2X1 U80 (.Y(\ab<1][4> ),
	.A(n29),
	.B(n32));
   NOR2X1 U81 (.Y(\ab<1][3> ),
	.A(n30),
	.B(n32));
   NOR2X1 U82 (.Y(\ab<1][2> ),
	.A(n31),
	.B(n32));
   NOR2X1 U83 (.Y(\ab<1][0> ),
	.A(p2),
	.B(n32));
   NOR2X1 U84 (.Y(\ab<0][5> ),
	.A(n28),
	.B(p2));
   NOR2X1 U85 (.Y(\ab<0][4> ),
	.A(n29),
	.B(p2));
   NOR2X1 U86 (.Y(\ab<0][3> ),
	.A(n30),
	.B(p2));
   NOR2X1 U87 (.Y(\ab<0][2> ),
	.A(n31),
	.B(p2));
   NOR2X1 U88 (.Y(\ab<0][1> ),
	.A(n32),
	.B(p2));
endmodule

module polynomial_a3_b2_c9_d1_in_bits6_out_bits24_DW02_mult_0 (
	\A<11> , 
	\A<10> , 
	\A<9> , 
	\A<8> , 
	\A<7> , 
	\A<6> , 
	\A<5> , 
	\A<4> , 
	\A<3> , 
	\A<2> , 
	\A<1> , 
	\A<0> , 
	\B<5> , 
	\B<4> , 
	\B<3> , 
	\B<2> , 
	\B<1> , 
	\B<0> , 
	TC, 
	\PRODUCT<17> , 
	\PRODUCT<16> , 
	\PRODUCT<15> , 
	\PRODUCT<14> , 
	\PRODUCT<13> , 
	\PRODUCT<12> , 
	\PRODUCT<11> , 
	\PRODUCT<10> , 
	\PRODUCT<9> , 
	\PRODUCT<8> , 
	\PRODUCT<7> , 
	\PRODUCT<6> , 
	\PRODUCT<5> , 
	\PRODUCT<4> , 
	\PRODUCT<3> , 
	\PRODUCT<2> , 
	\PRODUCT<1> , 
	\PRODUCT<0> );
   input \A<11> ;
   input \A<10> ;
   input \A<9> ;
   input \A<8> ;
   input \A<7> ;
   input \A<6> ;
   input \A<5> ;
   input \A<4> ;
   input \A<3> ;
   input \A<2> ;
   input \A<1> ;
   input \A<0> ;
   input \B<5> ;
   input \B<4> ;
   input \B<3> ;
   input \B<2> ;
   input \B<1> ;
   input \B<0> ;
   input TC;
   output \PRODUCT<17> ;
   output \PRODUCT<16> ;
   output \PRODUCT<15> ;
   output \PRODUCT<14> ;
   output \PRODUCT<13> ;
   output \PRODUCT<12> ;
   output \PRODUCT<11> ;
   output \PRODUCT<10> ;
   output \PRODUCT<9> ;
   output \PRODUCT<8> ;
   output \PRODUCT<7> ;
   output \PRODUCT<6> ;
   output \PRODUCT<5> ;
   output \PRODUCT<4> ;
   output \PRODUCT<3> ;
   output \PRODUCT<2> ;
   output \PRODUCT<1> ;
   output \PRODUCT<0> ;

   // Internal wires
   wire FE_OFN46_n39;
   wire FE_OFN45_n39;
   wire FE_OFN44_n38;
   wire \ab<11][5> ;
   wire \ab<11][4> ;
   wire \ab<11][3> ;
   wire \ab<11][2> ;
   wire \ab<11][1> ;
   wire \ab<11][0> ;
   wire \ab<10][5> ;
   wire \ab<10][4> ;
   wire \ab<10][3> ;
   wire \ab<10][2> ;
   wire \ab<10][1> ;
   wire \ab<10][0> ;
   wire \ab<9][5> ;
   wire \ab<9][4> ;
   wire \ab<9][3> ;
   wire \ab<9][2> ;
   wire \ab<9][1> ;
   wire \ab<9][0> ;
   wire \ab<8][5> ;
   wire \ab<8][4> ;
   wire \ab<8][3> ;
   wire \ab<8][2> ;
   wire \ab<8][1> ;
   wire \ab<8][0> ;
   wire \ab<7][5> ;
   wire \ab<7][4> ;
   wire \ab<7][3> ;
   wire \ab<7][2> ;
   wire \ab<7][1> ;
   wire \ab<7][0> ;
   wire \ab<6][5> ;
   wire \ab<6][4> ;
   wire \ab<6][3> ;
   wire \ab<6][2> ;
   wire \ab<6][1> ;
   wire \ab<6][0> ;
   wire \ab<5][5> ;
   wire \ab<5][4> ;
   wire \ab<5][3> ;
   wire \ab<5][2> ;
   wire \ab<5][1> ;
   wire \ab<5][0> ;
   wire \ab<4][5> ;
   wire \ab<4][4> ;
   wire \ab<4][3> ;
   wire \ab<4][2> ;
   wire \ab<4][1> ;
   wire \ab<4][0> ;
   wire \ab<3][5> ;
   wire \ab<3][4> ;
   wire \ab<3][3> ;
   wire \ab<3][2> ;
   wire \ab<3][1> ;
   wire \ab<3][0> ;
   wire \ab<2][5> ;
   wire \ab<2][4> ;
   wire \ab<2][3> ;
   wire \ab<2][2> ;
   wire \ab<2][1> ;
   wire \ab<2][0> ;
   wire \ab<1][5> ;
   wire \ab<1][4> ;
   wire \ab<1][3> ;
   wire \ab<1][2> ;
   wire \ab<1][1> ;
   wire \ab<1][0> ;
   wire \ab<0][5> ;
   wire \ab<0][4> ;
   wire \ab<0][3> ;
   wire \ab<0][2> ;
   wire \ab<0][1> ;
   wire \CARRYB<11][4> ;
   wire \CARRYB<11][3> ;
   wire \CARRYB<11][2> ;
   wire \CARRYB<11][1> ;
   wire \CARRYB<11][0> ;
   wire \CARRYB<10][4> ;
   wire \CARRYB<10][3> ;
   wire \CARRYB<10][2> ;
   wire \CARRYB<10][1> ;
   wire \CARRYB<10][0> ;
   wire \CARRYB<9][4> ;
   wire \CARRYB<9][3> ;
   wire \CARRYB<9][2> ;
   wire \CARRYB<9][1> ;
   wire \CARRYB<9][0> ;
   wire \CARRYB<8][4> ;
   wire \CARRYB<8][3> ;
   wire \CARRYB<8][2> ;
   wire \CARRYB<8][1> ;
   wire \CARRYB<8][0> ;
   wire \CARRYB<7][4> ;
   wire \CARRYB<7][3> ;
   wire \CARRYB<7][2> ;
   wire \CARRYB<7][1> ;
   wire \CARRYB<7][0> ;
   wire \CARRYB<6][4> ;
   wire \CARRYB<6][3> ;
   wire \CARRYB<6][2> ;
   wire \CARRYB<6][1> ;
   wire \CARRYB<6][0> ;
   wire \CARRYB<5][4> ;
   wire \CARRYB<5][3> ;
   wire \CARRYB<5][2> ;
   wire \CARRYB<5][1> ;
   wire \CARRYB<5][0> ;
   wire \CARRYB<4][4> ;
   wire \CARRYB<4][3> ;
   wire \CARRYB<4][2> ;
   wire \CARRYB<4][1> ;
   wire \CARRYB<4][0> ;
   wire \CARRYB<3][4> ;
   wire \CARRYB<3][3> ;
   wire \CARRYB<3][2> ;
   wire \CARRYB<3][1> ;
   wire \CARRYB<3][0> ;
   wire \CARRYB<2][4> ;
   wire \CARRYB<2][3> ;
   wire \CARRYB<2][2> ;
   wire \CARRYB<2][1> ;
   wire \CARRYB<2][0> ;
   wire \CARRYB<1][4> ;
   wire \CARRYB<1][3> ;
   wire \CARRYB<1][2> ;
   wire \CARRYB<1][1> ;
   wire \CARRYB<1][0> ;
   wire \SUMB<11][4> ;
   wire \SUMB<11][3> ;
   wire \SUMB<11][2> ;
   wire \SUMB<11][1> ;
   wire \SUMB<10][4> ;
   wire \SUMB<10][3> ;
   wire \SUMB<10][2> ;
   wire \SUMB<10][1> ;
   wire \SUMB<9][4> ;
   wire \SUMB<9][3> ;
   wire \SUMB<9][2> ;
   wire \SUMB<9][1> ;
   wire \SUMB<8][4> ;
   wire \SUMB<8][3> ;
   wire \SUMB<8][2> ;
   wire \SUMB<8][1> ;
   wire \SUMB<7][4> ;
   wire \SUMB<7][3> ;
   wire \SUMB<7][2> ;
   wire \SUMB<7][1> ;
   wire \SUMB<6][4> ;
   wire \SUMB<6][3> ;
   wire \SUMB<6][2> ;
   wire \SUMB<6][1> ;
   wire \SUMB<5][4> ;
   wire \SUMB<5][3> ;
   wire \SUMB<5][2> ;
   wire \SUMB<5][1> ;
   wire \SUMB<4][4> ;
   wire \SUMB<4][3> ;
   wire \SUMB<4][2> ;
   wire \SUMB<4][1> ;
   wire \SUMB<3][4> ;
   wire \SUMB<3][3> ;
   wire \SUMB<3][2> ;
   wire \SUMB<3][1> ;
   wire \SUMB<2][4> ;
   wire \SUMB<2][3> ;
   wire \SUMB<2][2> ;
   wire \SUMB<2][1> ;
   wire \SUMB<1][4> ;
   wire \SUMB<1][3> ;
   wire \SUMB<1][2> ;
   wire \SUMB<1][1> ;
   wire \A1<14> ;
   wire \A1<13> ;
   wire \A1<12> ;
   wire \A1<11> ;
   wire \A2<15> ;
   wire \A2<14> ;
   wire \A2<13> ;
   wire \A2<12> ;
   wire \A2<11> ;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n11;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire n20;
   wire n21;
   wire n22;
   wire n23;
   wire n24;
   wire n25;
   wire n26;
   wire n27;
   wire n28;
   wire n29;
   wire n30;
   wire n31;
   wire n32;
   wire n33;
   wire n34;
   wire n35;
   wire n37;
   wire n38;
   wire n39;
   wire n40;
   wire n41;

   INVX1 FE_OFC44_n39 (.Y(FE_OFN46_n39),
	.A(FE_OFN45_n39));
   INVXL FE_OFC43_n39 (.Y(FE_OFN45_n39),
	.A(n39));
   BUFX2 FE_OFC42_n38 (.Y(FE_OFN44_n38),
	.A(n38));
   ADDFX1 S2_9_3 (.CO(\CARRYB<9][3> ),
	.S(\SUMB<9][3> ),
	.A(\ab<9][3> ),
	.B(\CARRYB<8][3> ),
	.CI(\SUMB<8][4> ));
   ADDFX1 S2_9_2 (.CO(\CARRYB<9][2> ),
	.S(\SUMB<9][2> ),
	.A(\ab<9][2> ),
	.B(\CARRYB<8][2> ),
	.CI(\SUMB<8][3> ));
   ADDFX1 S2_6_2 (.CO(\CARRYB<6][2> ),
	.S(\SUMB<6][2> ),
	.A(\ab<6][2> ),
	.B(\CARRYB<5][2> ),
	.CI(\SUMB<5][3> ));
   ADDFX1 S2_6_3 (.CO(\CARRYB<6][3> ),
	.S(\SUMB<6][3> ),
	.A(\ab<6][3> ),
	.B(\CARRYB<5][3> ),
	.CI(\SUMB<5][4> ));
   ADDFX1 S2_5_2 (.CO(\CARRYB<5][2> ),
	.S(\SUMB<5][2> ),
	.A(\ab<5][2> ),
	.B(\CARRYB<4][2> ),
	.CI(\SUMB<4][3> ));
   ADDFX1 S2_5_3 (.CO(\CARRYB<5][3> ),
	.S(\SUMB<5][3> ),
	.A(\ab<5][3> ),
	.B(\CARRYB<4][3> ),
	.CI(\SUMB<4][4> ));
   ADDFX1 S2_4_2 (.CO(\CARRYB<4][2> ),
	.S(\SUMB<4][2> ),
	.A(\ab<4][2> ),
	.B(\CARRYB<3][2> ),
	.CI(\SUMB<3][3> ));
   ADDFX1 S2_4_3 (.CO(\CARRYB<4][3> ),
	.S(\SUMB<4][3> ),
	.A(\ab<4][3> ),
	.B(\CARRYB<3][3> ),
	.CI(\SUMB<3][4> ));
   ADDFX1 S2_3_2 (.CO(\CARRYB<3][2> ),
	.S(\SUMB<3][2> ),
	.A(\ab<3][2> ),
	.B(\CARRYB<2][2> ),
	.CI(\SUMB<2][3> ));
   ADDFX1 S2_3_3 (.CO(\CARRYB<3][3> ),
	.S(\SUMB<3][3> ),
	.A(\ab<3][3> ),
	.B(\CARRYB<2][3> ),
	.CI(\SUMB<2][4> ));
   ADDFX1 S2_2_2 (.CO(\CARRYB<2][2> ),
	.S(\SUMB<2][2> ),
	.A(\ab<2][2> ),
	.B(\CARRYB<1][2> ),
	.CI(\SUMB<1][3> ));
   ADDFX1 S2_10_3 (.CO(\CARRYB<10][3> ),
	.S(\SUMB<10][3> ),
	.A(\ab<10][3> ),
	.B(\CARRYB<9][3> ),
	.CI(\SUMB<9][4> ));
   ADDFX1 S2_10_2 (.CO(\CARRYB<10][2> ),
	.S(\SUMB<10][2> ),
	.A(\ab<10][2> ),
	.B(\CARRYB<9][2> ),
	.CI(\SUMB<9][3> ));
   ADDFX1 S2_10_1 (.CO(\CARRYB<10][1> ),
	.S(\SUMB<10][1> ),
	.A(\ab<10][1> ),
	.B(\CARRYB<9][1> ),
	.CI(\SUMB<9][2> ));
   ADDFX1 S2_8_3 (.CO(\CARRYB<8][3> ),
	.S(\SUMB<8][3> ),
	.A(\ab<8][3> ),
	.B(\CARRYB<7][3> ),
	.CI(\SUMB<7][4> ));
   ADDFX1 S3_10_4 (.CO(\CARRYB<10][4> ),
	.S(\SUMB<10][4> ),
	.A(\ab<10][4> ),
	.B(\CARRYB<9][4> ),
	.CI(\ab<9][5> ));
   ADDFX1 S3_6_4 (.CO(\CARRYB<6][4> ),
	.S(\SUMB<6][4> ),
	.A(\ab<6][4> ),
	.B(\CARRYB<5][4> ),
	.CI(\ab<5][5> ));
   ADDFX1 S3_5_4 (.CO(\CARRYB<5][4> ),
	.S(\SUMB<5][4> ),
	.A(\ab<5][4> ),
	.B(\CARRYB<4][4> ),
	.CI(\ab<4][5> ));
   ADDFX1 S3_4_4 (.CO(\CARRYB<4][4> ),
	.S(\SUMB<4][4> ),
	.A(\ab<4][4> ),
	.B(\CARRYB<3][4> ),
	.CI(\ab<3][5> ));
   ADDFX1 S3_3_4 (.CO(\CARRYB<3][4> ),
	.S(\SUMB<3][4> ),
	.A(\ab<3][4> ),
	.B(\CARRYB<2][4> ),
	.CI(\ab<2][5> ));
   ADDFX1 S3_9_4 (.CO(\CARRYB<9][4> ),
	.S(\SUMB<9][4> ),
	.A(\ab<9][4> ),
	.B(\CARRYB<8][4> ),
	.CI(\ab<8][5> ));
   ADDFX1 S3_2_4 (.CO(\CARRYB<2][4> ),
	.S(\SUMB<2][4> ),
	.A(\ab<2][4> ),
	.B(\CARRYB<1][4> ),
	.CI(\ab<1][5> ));
   ADDFX1 S2_7_3 (.CO(\CARRYB<7][3> ),
	.S(\SUMB<7][3> ),
	.A(\ab<7][3> ),
	.B(\CARRYB<6][3> ),
	.CI(\SUMB<6][4> ));
   ADDFX1 S3_7_4 (.CO(\CARRYB<7][4> ),
	.S(\SUMB<7][4> ),
	.A(\ab<7][4> ),
	.B(\CARRYB<6][4> ),
	.CI(\ab<6][5> ));
   ADDFX1 S3_8_4 (.CO(\CARRYB<8][4> ),
	.S(\SUMB<8][4> ),
	.A(\ab<8][4> ),
	.B(\CARRYB<7][4> ),
	.CI(\ab<7][5> ));
   ADDFX1 S1_2_0 (.CO(\CARRYB<2][0> ),
	.S(\PRODUCT<2> ),
	.A(\ab<2][0> ),
	.B(\CARRYB<1][0> ),
	.CI(\SUMB<1][1> ));
   ADDFX1 S2_2_1 (.CO(\CARRYB<2][1> ),
	.S(\SUMB<2][1> ),
	.A(\ab<2][1> ),
	.B(\CARRYB<1][1> ),
	.CI(\SUMB<1][2> ));
   ADDFX1 S2_2_3 (.CO(\CARRYB<2][3> ),
	.S(\SUMB<2][3> ),
	.A(\ab<2][3> ),
	.B(\CARRYB<1][3> ),
	.CI(\SUMB<1][4> ));
   ADDFX1 S1_3_0 (.CO(\CARRYB<3][0> ),
	.S(\PRODUCT<3> ),
	.A(\ab<3][0> ),
	.B(\CARRYB<2][0> ),
	.CI(\SUMB<2][1> ));
   ADDFX1 S2_3_1 (.CO(\CARRYB<3][1> ),
	.S(\SUMB<3][1> ),
	.A(\ab<3][1> ),
	.B(\CARRYB<2][1> ),
	.CI(\SUMB<2][2> ));
   ADDFX1 S1_10_0 (.CO(\CARRYB<10][0> ),
	.S(\PRODUCT<10> ),
	.A(\ab<10][0> ),
	.B(\CARRYB<9][0> ),
	.CI(\SUMB<9][1> ));
   ADDFX1 S1_9_0 (.CO(\CARRYB<9][0> ),
	.S(\PRODUCT<9> ),
	.A(\ab<9][0> ),
	.B(\CARRYB<8][0> ),
	.CI(\SUMB<8][1> ));
   ADDFX1 S2_9_1 (.CO(\CARRYB<9][1> ),
	.S(\SUMB<9][1> ),
	.A(\ab<9][1> ),
	.B(\CARRYB<8][1> ),
	.CI(\SUMB<8][2> ));
   ADDFX1 S1_8_0 (.CO(\CARRYB<8][0> ),
	.S(\PRODUCT<8> ),
	.A(\ab<8][0> ),
	.B(\CARRYB<7][0> ),
	.CI(\SUMB<7][1> ));
   ADDFX1 S2_8_1 (.CO(\CARRYB<8][1> ),
	.S(\SUMB<8][1> ),
	.A(\ab<8][1> ),
	.B(\CARRYB<7][1> ),
	.CI(\SUMB<7][2> ));
   ADDFX1 S2_8_2 (.CO(\CARRYB<8][2> ),
	.S(\SUMB<8][2> ),
	.A(\ab<8][2> ),
	.B(\CARRYB<7][2> ),
	.CI(\SUMB<7][3> ));
   ADDFX1 S1_7_0 (.CO(\CARRYB<7][0> ),
	.S(\PRODUCT<7> ),
	.A(\ab<7][0> ),
	.B(\CARRYB<6][0> ),
	.CI(\SUMB<6][1> ));
   ADDFX1 S2_7_1 (.CO(\CARRYB<7][1> ),
	.S(\SUMB<7][1> ),
	.A(\ab<7][1> ),
	.B(\CARRYB<6][1> ),
	.CI(\SUMB<6][2> ));
   ADDFX1 S2_7_2 (.CO(\CARRYB<7][2> ),
	.S(\SUMB<7][2> ),
	.A(\ab<7][2> ),
	.B(\CARRYB<6][2> ),
	.CI(\SUMB<6][3> ));
   ADDFX1 S1_6_0 (.CO(\CARRYB<6][0> ),
	.S(\PRODUCT<6> ),
	.A(\ab<6][0> ),
	.B(\CARRYB<5][0> ),
	.CI(\SUMB<5][1> ));
   ADDFX1 S2_6_1 (.CO(\CARRYB<6][1> ),
	.S(\SUMB<6][1> ),
	.A(\ab<6][1> ),
	.B(\CARRYB<5][1> ),
	.CI(\SUMB<5][2> ));
   ADDFX1 S1_5_0 (.CO(\CARRYB<5][0> ),
	.S(\PRODUCT<5> ),
	.A(\ab<5][0> ),
	.B(\CARRYB<4][0> ),
	.CI(\SUMB<4][1> ));
   ADDFX1 S2_5_1 (.CO(\CARRYB<5][1> ),
	.S(\SUMB<5][1> ),
	.A(\ab<5][1> ),
	.B(\CARRYB<4][1> ),
	.CI(\SUMB<4][2> ));
   ADDFX1 S1_4_0 (.CO(\CARRYB<4][0> ),
	.S(\PRODUCT<4> ),
	.A(\ab<4][0> ),
	.B(\CARRYB<3][0> ),
	.CI(\SUMB<3][1> ));
   ADDFX1 S2_4_1 (.CO(\CARRYB<4][1> ),
	.S(\SUMB<4][1> ),
	.A(\ab<4][1> ),
	.B(\CARRYB<3][1> ),
	.CI(\SUMB<3][2> ));
   ADDFX1 S4_0 (.CO(\CARRYB<11][0> ),
	.S(\PRODUCT<11> ),
	.A(\ab<11][0> ),
	.B(\CARRYB<10][0> ),
	.CI(\SUMB<10][1> ));
   ADDFX1 S4_1 (.CO(\CARRYB<11][1> ),
	.S(\SUMB<11][1> ),
	.A(\ab<11][1> ),
	.B(\CARRYB<10][1> ),
	.CI(\SUMB<10][2> ));
   ADDFX1 S5_4 (.CO(\CARRYB<11][4> ),
	.S(\SUMB<11][4> ),
	.A(\ab<11][4> ),
	.B(\CARRYB<10][4> ),
	.CI(\ab<10][5> ));
   ADDFX1 S4_3 (.CO(\CARRYB<11][3> ),
	.S(\SUMB<11][3> ),
	.A(\ab<11][3> ),
	.B(\CARRYB<10][3> ),
	.CI(\SUMB<10][4> ));
   ADDFX1 S4_2 (.CO(\CARRYB<11][2> ),
	.S(\SUMB<11][2> ),
	.A(\ab<11][2> ),
	.B(\CARRYB<10][2> ),
	.CI(\SUMB<10][3> ));
   INVX1 U2 (.Y(n29),
	.A(\A<8> ));
   INVX1 U3 (.Y(n28),
	.A(\A<9> ));
   INVX1 U4 (.Y(n30),
	.A(\A<7> ));
   INVX1 U5 (.Y(n25),
	.A(n14));
   XNOR2X1 U6 (.Y(\PRODUCT<17> ),
	.A(n24),
	.B(\A2<15> ));
   NOR2X1 U7 (.Y(\A2<15> ),
	.A(n2),
	.B(n3));
   INVX1 U8 (.Y(n27),
	.A(\A<10> ));
   INVX1 U10 (.Y(n31),
	.A(\A<6> ));
   INVX1 U11 (.Y(n26),
	.A(\A<11> ));
   INVX1 U12 (.Y(n12),
	.A(\ab<1][4> ));
   INVX1 U13 (.Y(n10),
	.A(\ab<1][3> ));
   INVX1 U14 (.Y(n8),
	.A(\ab<1][2> ));
   INVX1 U15 (.Y(n6),
	.A(\ab<1][1> ));
   CLKXOR2X1 U16 (.Y(\PRODUCT<12> ),
	.A(\CARRYB<11][0> ),
	.B(\SUMB<11][1> ));
   CLKXOR2X1 U17 (.Y(\A1<12> ),
	.A(\CARRYB<11][2> ),
	.B(\SUMB<11][3> ));
   CLKXOR2X1 U18 (.Y(\A1<13> ),
	.A(\CARRYB<11][3> ),
	.B(\SUMB<11][4> ));
   CLKXOR2X1 U19 (.Y(\A1<11> ),
	.A(\CARRYB<11][1> ),
	.B(\SUMB<11][2> ));
   INVX1 U20 (.Y(n33),
	.A(\A<4> ));
   INVX1 U21 (.Y(n32),
	.A(\A<5> ));
   INVX1 U22 (.Y(n34),
	.A(\A<3> ));
   AND2X1 U23 (.Y(\A2<11> ),
	.A(\CARRYB<11][0> ),
	.B(\SUMB<11][1> ));
   AND2X1 U24 (.Y(\A2<12> ),
	.A(\SUMB<11][2> ),
	.B(\CARRYB<11][1> ));
   AND2X1 U25 (.Y(\A2<13> ),
	.A(\SUMB<11][3> ),
	.B(\CARRYB<11][2> ));
   CLKXOR2X1 U26 (.Y(\PRODUCT<1> ),
	.A(\ab<1][0> ),
	.B(\ab<0][1> ));
   INVX1 U27 (.Y(n13),
	.A(\ab<0][5> ));
   INVX1 U28 (.Y(n11),
	.A(\ab<0][4> ));
   INVX1 U29 (.Y(n9),
	.A(\ab<0][3> ));
   INVX1 U30 (.Y(n7),
	.A(\ab<0][2> ));
   INVX1 U31 (.Y(n5),
	.A(\ab<0][1> ));
   INVX1 U32 (.Y(n4),
	.A(\ab<1][0> ));
   CLKXOR2X1 U33 (.Y(\A1<14> ),
	.A(\CARRYB<11][4> ),
	.B(\ab<11][5> ));
   INVX1 U34 (.Y(n3),
	.A(\CARRYB<11][4> ));
   AND2X1 U35 (.Y(\A2<14> ),
	.A(\SUMB<11][4> ),
	.B(\CARRYB<11][3> ));
   INVX1 U36 (.Y(n2),
	.A(\ab<11][5> ));
   NOR2X1 U37 (.Y(\CARRYB<1][3> ),
	.A(n10),
	.B(n11));
   CLKXOR2X1 U38 (.Y(\SUMB<1][4> ),
	.A(\ab<1][4> ),
	.B(\ab<0][5> ));
   NOR2X1 U39 (.Y(\CARRYB<1][1> ),
	.A(n6),
	.B(n7));
   CLKXOR2X1 U40 (.Y(\SUMB<1][2> ),
	.A(\ab<1][2> ),
	.B(\ab<0][3> ));
   NOR2X1 U41 (.Y(\CARRYB<1][0> ),
	.A(n4),
	.B(n5));
   CLKXOR2X1 U42 (.Y(\SUMB<1][1> ),
	.A(\ab<1][1> ),
	.B(\ab<0][2> ));
   NOR2X1 U43 (.Y(\CARRYB<1][4> ),
	.A(n12),
	.B(n13));
   NOR2X1 U44 (.Y(\CARRYB<1][2> ),
	.A(n8),
	.B(n9));
   CLKXOR2X1 U45 (.Y(\SUMB<1][3> ),
	.A(\ab<1][3> ),
	.B(\ab<0][4> ));
   INVX1 U46 (.Y(n35),
	.A(\A<2> ));
   INVX2 U48 (.Y(n37),
	.A(\B<5> ));
   INVX2 U49 (.Y(n41),
	.A(\B<1> ));
   INVX1 U50 (.Y(n39),
	.A(\B<3> ));
   INVX2 U51 (.Y(n40),
	.A(\B<2> ));
   INVX1 U52 (.Y(n38),
	.A(\B<4> ));
   NAND2X1 U53 (.Y(n14),
	.A(\A2<11> ),
	.B(\A1<11> ));
   NOR2X1 U54 (.Y(n15),
	.A(\A2<11> ),
	.B(\A1<11> ));
   NOR2BX1 U55 (.Y(\PRODUCT<13> ),
	.AN(n14),
	.B(n15));
   XNOR2X1 U56 (.Y(n16),
	.A(\A2<12> ),
	.B(\A1<12> ));
   XNOR2X1 U57 (.Y(\PRODUCT<14> ),
	.A(n25),
	.B(n16));
   OR2X1 U58 (.Y(n17),
	.A(\A1<12> ),
	.B(n25));
   AO22X1 U59 (.Y(n20),
	.A0(n25),
	.A1(\A1<12> ),
	.B0(n17),
	.B1(\A2<12> ));
   XNOR2X1 U60 (.Y(n18),
	.A(\A2<13> ),
	.B(\A1<13> ));
   XNOR2X1 U61 (.Y(\PRODUCT<15> ),
	.A(n20),
	.B(n18));
   OR2X1 U62 (.Y(n19),
	.A(\A1<13> ),
	.B(n20));
   AO22X1 U63 (.Y(n23),
	.A0(n20),
	.A1(\A1<13> ),
	.B0(n19),
	.B1(\A2<13> ));
   XNOR2X1 U64 (.Y(n21),
	.A(\A2<14> ),
	.B(\A1<14> ));
   XNOR2X1 U65 (.Y(\PRODUCT<16> ),
	.A(n23),
	.B(n21));
   OR2X1 U66 (.Y(n22),
	.A(\A1<14> ),
	.B(n23));
   AOI22X1 U67 (.Y(n24),
	.A0(n23),
	.A1(\A1<14> ),
	.B0(n22),
	.B1(\A2<14> ));
   NOR2X1 U68 (.Y(\ab<9][5> ),
	.A(n28),
	.B(n37));
   NOR2X1 U69 (.Y(\ab<9][4> ),
	.A(n28),
	.B(FE_OFN44_n38));
   NOR2X1 U70 (.Y(\ab<9][3> ),
	.A(n28),
	.B(n39));
   NOR2X1 U71 (.Y(\ab<9][2> ),
	.A(n28),
	.B(n40));
   NOR2X1 U72 (.Y(\ab<9][1> ),
	.A(n28),
	.B(n41));
   NOR2X1 U73 (.Y(\ab<9][0> ),
	.A(n28),
	.B(\A<0> ));
   NOR2X1 U74 (.Y(\ab<8][5> ),
	.A(n37),
	.B(n29));
   NOR2X1 U75 (.Y(\ab<8][4> ),
	.A(FE_OFN44_n38),
	.B(n29));
   NOR2X1 U76 (.Y(\ab<8][3> ),
	.A(n39),
	.B(n29));
   NOR2X1 U77 (.Y(\ab<8][2> ),
	.A(n40),
	.B(n29));
   NOR2X1 U78 (.Y(\ab<8][1> ),
	.A(n41),
	.B(n29));
   NOR2X1 U79 (.Y(\ab<8][0> ),
	.A(\A<0> ),
	.B(n29));
   NOR2X1 U80 (.Y(\ab<7][5> ),
	.A(n37),
	.B(n30));
   NOR2X1 U81 (.Y(\ab<7][4> ),
	.A(FE_OFN44_n38),
	.B(n30));
   NOR2X1 U82 (.Y(\ab<7][3> ),
	.A(n39),
	.B(n30));
   NOR2X1 U83 (.Y(\ab<7][2> ),
	.A(n40),
	.B(n30));
   NOR2X1 U84 (.Y(\ab<7][1> ),
	.A(n41),
	.B(n30));
   NOR2X1 U85 (.Y(\ab<7][0> ),
	.A(\A<0> ),
	.B(n30));
   NOR2X1 U86 (.Y(\ab<6][5> ),
	.A(n37),
	.B(n31));
   NOR2X1 U87 (.Y(\ab<6][4> ),
	.A(FE_OFN44_n38),
	.B(n31));
   NOR2X1 U88 (.Y(\ab<6][3> ),
	.A(FE_OFN46_n39),
	.B(n31));
   NOR2X1 U89 (.Y(\ab<6][2> ),
	.A(n40),
	.B(n31));
   NOR2X1 U90 (.Y(\ab<6][1> ),
	.A(n41),
	.B(n31));
   NOR2X1 U91 (.Y(\ab<6][0> ),
	.A(\A<0> ),
	.B(n31));
   NOR2X1 U92 (.Y(\ab<5][5> ),
	.A(n37),
	.B(n32));
   NOR2X1 U93 (.Y(\ab<5][4> ),
	.A(FE_OFN44_n38),
	.B(n32));
   NOR2X1 U94 (.Y(\ab<5][3> ),
	.A(FE_OFN46_n39),
	.B(n32));
   NOR2X1 U95 (.Y(\ab<5][2> ),
	.A(n40),
	.B(n32));
   NOR2X1 U96 (.Y(\ab<5][1> ),
	.A(n41),
	.B(n32));
   NOR2X1 U97 (.Y(\ab<5][0> ),
	.A(\A<0> ),
	.B(n32));
   NOR2X1 U98 (.Y(\ab<4][5> ),
	.A(n37),
	.B(n33));
   NOR2X1 U99 (.Y(\ab<4][4> ),
	.A(FE_OFN44_n38),
	.B(n33));
   NOR2X1 U100 (.Y(\ab<4][3> ),
	.A(FE_OFN46_n39),
	.B(n33));
   NOR2X1 U101 (.Y(\ab<4][2> ),
	.A(n40),
	.B(n33));
   NOR2X1 U102 (.Y(\ab<4][1> ),
	.A(n41),
	.B(n33));
   NOR2X1 U103 (.Y(\ab<4][0> ),
	.A(\A<0> ),
	.B(n33));
   NOR2X1 U104 (.Y(\ab<3][5> ),
	.A(n37),
	.B(n34));
   NOR2X1 U105 (.Y(\ab<3][4> ),
	.A(FE_OFN44_n38),
	.B(n34));
   NOR2X1 U106 (.Y(\ab<3][3> ),
	.A(FE_OFN46_n39),
	.B(n34));
   NOR2X1 U107 (.Y(\ab<3][2> ),
	.A(n40),
	.B(n34));
   NOR2X1 U108 (.Y(\ab<3][1> ),
	.A(n41),
	.B(n34));
   NOR2X1 U109 (.Y(\ab<3][0> ),
	.A(\A<0> ),
	.B(n34));
   NOR2X1 U110 (.Y(\ab<2][5> ),
	.A(n37),
	.B(n35));
   NOR2X1 U111 (.Y(\ab<2][4> ),
	.A(FE_OFN44_n38),
	.B(n35));
   NOR2X1 U112 (.Y(\ab<2][3> ),
	.A(FE_OFN46_n39),
	.B(n35));
   NOR2X1 U113 (.Y(\ab<2][2> ),
	.A(n40),
	.B(n35));
   NOR2X1 U114 (.Y(\ab<2][1> ),
	.A(n41),
	.B(n35));
   NOR2X1 U115 (.Y(\ab<2][0> ),
	.A(\A<0> ),
	.B(n35));
   NOR2X1 U116 (.Y(\ab<1][5> ),
	.A(n37),
	.B(\A<1> ));
   NOR2X1 U117 (.Y(\ab<1][4> ),
	.A(FE_OFN44_n38),
	.B(\A<1> ));
   NOR2X1 U118 (.Y(\ab<1][3> ),
	.A(FE_OFN46_n39),
	.B(\A<1> ));
   NOR2X1 U119 (.Y(\ab<1][2> ),
	.A(n40),
	.B(\A<1> ));
   NOR2X1 U120 (.Y(\ab<1][1> ),
	.A(n41),
	.B(\A<1> ));
   NOR2X1 U121 (.Y(\ab<1][0> ),
	.A(\A<0> ),
	.B(\A<1> ));
   NOR2X1 U122 (.Y(\ab<11][5> ),
	.A(n37),
	.B(n26));
   NOR2X1 U123 (.Y(\ab<11][4> ),
	.A(FE_OFN44_n38),
	.B(n26));
   NOR2X1 U124 (.Y(\ab<11][3> ),
	.A(n39),
	.B(n26));
   NOR2X1 U125 (.Y(\ab<11][2> ),
	.A(n40),
	.B(n26));
   NOR2X1 U126 (.Y(\ab<11][1> ),
	.A(n41),
	.B(n26));
   NOR2X1 U127 (.Y(\ab<11][0> ),
	.A(\A<0> ),
	.B(n26));
   NOR2X1 U128 (.Y(\ab<10][5> ),
	.A(n37),
	.B(n27));
   NOR2X1 U129 (.Y(\ab<10][4> ),
	.A(FE_OFN44_n38),
	.B(n27));
   NOR2X1 U130 (.Y(\ab<10][3> ),
	.A(n39),
	.B(n27));
   NOR2X1 U131 (.Y(\ab<10][2> ),
	.A(n40),
	.B(n27));
   NOR2X1 U132 (.Y(\ab<10][1> ),
	.A(n41),
	.B(n27));
   NOR2X1 U133 (.Y(\ab<10][0> ),
	.A(\A<0> ),
	.B(n27));
   NOR2X1 U134 (.Y(\ab<0][5> ),
	.A(n37),
	.B(\A<0> ));
   NOR2X1 U135 (.Y(\ab<0][4> ),
	.A(FE_OFN44_n38),
	.B(\A<0> ));
   NOR2X1 U136 (.Y(\ab<0][3> ),
	.A(FE_OFN46_n39),
	.B(\A<0> ));
   NOR2X1 U137 (.Y(\ab<0][2> ),
	.A(n40),
	.B(\A<0> ));
   NOR2X1 U138 (.Y(\ab<0][1> ),
	.A(n41),
	.B(\A<0> ));
endmodule

module polynomial_a3_b2_c9_d1_in_bits6_out_bits24_DW01_add_0 (
	\A<20> , 
	\A<19> , 
	\A<18> , 
	\A<17> , 
	\A<16> , 
	\A<15> , 
	\A<14> , 
	\A<13> , 
	\A<12> , 
	\A<11> , 
	\A<10> , 
	\A<9> , 
	\A<8> , 
	\A<7> , 
	\A<6> , 
	\A<5> , 
	\A<4> , 
	\A<3> , 
	\A<2> , 
	\A<1> , 
	\A<0> , 
	\B<20> , 
	\B<19> , 
	\B<18> , 
	\B<17> , 
	\B<16> , 
	\B<15> , 
	\B<14> , 
	\B<13> , 
	\B<12> , 
	\B<11> , 
	\B<10> , 
	\B<9> , 
	\B<8> , 
	\B<7> , 
	\B<6> , 
	\B<5> , 
	\B<4> , 
	\B<3> , 
	\B<2> , 
	\B<1> , 
	\B<0> , 
	CI, 
	\SUM<20> , 
	\SUM<19> , 
	\SUM<18> , 
	\SUM<17> , 
	\SUM<16> , 
	\SUM<15> , 
	\SUM<14> , 
	\SUM<13> , 
	\SUM<12> , 
	\SUM<11> , 
	\SUM<10> , 
	\SUM<9> , 
	\SUM<8> , 
	\SUM<7> , 
	\SUM<6> , 
	\SUM<5> , 
	\SUM<4> , 
	\SUM<3> , 
	\SUM<2> , 
	\SUM<1> , 
	\SUM<0> , 
	CO, 
	N3);
   input \A<20> ;
   input \A<19> ;
   input \A<18> ;
   input \A<17> ;
   input \A<16> ;
   input \A<15> ;
   input \A<14> ;
   input \A<13> ;
   input \A<12> ;
   input \A<11> ;
   input \A<10> ;
   input \A<9> ;
   input \A<8> ;
   input \A<7> ;
   input \A<6> ;
   input \A<5> ;
   input \A<4> ;
   input \A<3> ;
   input \A<2> ;
   input \A<1> ;
   input \A<0> ;
   input \B<20> ;
   input \B<19> ;
   input \B<18> ;
   input \B<17> ;
   input \B<16> ;
   input \B<15> ;
   input \B<14> ;
   input \B<13> ;
   input \B<12> ;
   input \B<11> ;
   input \B<10> ;
   input \B<9> ;
   input \B<8> ;
   input \B<7> ;
   input \B<6> ;
   input \B<5> ;
   input \B<4> ;
   input \B<3> ;
   input \B<2> ;
   input \B<1> ;
   input \B<0> ;
   input CI;
   output \SUM<20> ;
   output \SUM<19> ;
   output \SUM<18> ;
   output \SUM<17> ;
   output \SUM<16> ;
   output \SUM<15> ;
   output \SUM<14> ;
   output \SUM<13> ;
   output \SUM<12> ;
   output \SUM<11> ;
   output \SUM<10> ;
   output \SUM<9> ;
   output \SUM<8> ;
   output \SUM<7> ;
   output \SUM<6> ;
   output \SUM<5> ;
   output \SUM<4> ;
   output \SUM<3> ;
   output \SUM<2> ;
   output \SUM<1> ;
   output \SUM<0> ;
   output CO;
   input N3;

   // Internal wires
   wire \carry<18> ;
   wire \carry<17> ;
   wire \carry<16> ;
   wire \carry<15> ;
   wire \carry<14> ;
   wire \carry<13> ;
   wire \carry<12> ;
   wire \carry<11> ;
   wire \carry<10> ;
   wire \carry<9> ;
   wire \carry<8> ;
   wire \carry<7> ;
   wire \carry<6> ;
   wire \carry<5> ;
   wire \carry<4> ;
   wire \carry<3> ;
   wire \carry<2> ;
   wire n1;
   wire n3;
   wire n4;

   assign \SUM<18>  = \carry<18>  ;

   ADDFX1 U1_2 (.CO(\carry<3> ),
	.S(\SUM<2> ),
	.A(\A<2> ),
	.B(\B<2> ),
	.CI(\carry<2> ));
   ADDFX1 U1_3 (.CO(\carry<4> ),
	.S(\SUM<3> ),
	.A(\A<3> ),
	.B(\B<3> ),
	.CI(\carry<3> ));
   ADDFX1 U1_8 (.CO(\carry<9> ),
	.S(\SUM<8> ),
	.A(\A<8> ),
	.B(\B<8> ),
	.CI(\carry<8> ));
   ADDFX1 U1_7 (.CO(\carry<8> ),
	.S(\SUM<7> ),
	.A(\A<7> ),
	.B(\B<7> ),
	.CI(\carry<7> ));
   ADDFX1 U1_6 (.CO(\carry<7> ),
	.S(\SUM<6> ),
	.A(\A<6> ),
	.B(\B<6> ),
	.CI(\carry<6> ));
   ADDFX1 U1_5 (.CO(\carry<6> ),
	.S(\SUM<5> ),
	.A(\A<5> ),
	.B(\B<5> ),
	.CI(\carry<5> ));
   ADDFX1 U1_4 (.CO(\carry<5> ),
	.S(\SUM<4> ),
	.A(\A<4> ),
	.B(\B<4> ),
	.CI(\carry<4> ));
   ADDFX1 U1_12 (.CO(\carry<13> ),
	.S(\SUM<12> ),
	.A(\A<12> ),
	.B(\B<12> ),
	.CI(\carry<12> ));
   ADDFX1 U1_11 (.CO(\carry<12> ),
	.S(\SUM<11> ),
	.A(\A<11> ),
	.B(\B<11> ),
	.CI(\carry<11> ));
   ADDFX1 U1_10 (.CO(\carry<11> ),
	.S(\SUM<10> ),
	.A(\A<10> ),
	.B(\B<10> ),
	.CI(\carry<10> ));
   ADDFX1 U1_9 (.CO(\carry<10> ),
	.S(\SUM<9> ),
	.A(\A<9> ),
	.B(\B<9> ),
	.CI(\carry<9> ));
   ADDFX1 U1_15 (.CO(\carry<16> ),
	.S(\SUM<15> ),
	.A(\A<15> ),
	.B(\B<15> ),
	.CI(\carry<15> ));
   ADDFX1 U1_14 (.CO(\carry<15> ),
	.S(\SUM<14> ),
	.A(\A<14> ),
	.B(\B<14> ),
	.CI(\carry<14> ));
   ADDFX1 U1_13 (.CO(\carry<14> ),
	.S(\SUM<13> ),
	.A(\A<13> ),
	.B(\B<13> ),
	.CI(\carry<13> ));
   ADDFX1 U1_16 (.CO(\carry<17> ),
	.S(\SUM<16> ),
	.A(\A<16> ),
	.B(\B<16> ),
	.CI(\carry<16> ));
   CLKXOR2X1 U1 (.Y(\SUM<17> ),
	.A(\A<17> ),
	.B(\carry<17> ));
   NOR2X1 U2 (.Y(\carry<18> ),
	.A(n3),
	.B(n4));
   INVX1 U3 (.Y(n4),
	.A(\A<17> ));
   INVX1 U4 (.Y(n3),
	.A(\carry<17> ));
   XOR2X4 U5 (.Y(\SUM<1> ),
	.A(\B<1> ),
	.B(\A<1> ));
   NOR2X1 U6 (.Y(\carry<2> ),
	.A(n1),
	.B(N3));
   INVX1 U8 (.Y(n1),
	.A(\A<1> ));
endmodule

module polynomial_a3_b2_c9_d1_in_bits6_out_bits24 (
	clock, 
	valid_in, 
	reset, 
	valid_out, 
	\x<5> , 
	\x<4> , 
	\x<3> , 
	\x<2> , 
	\x<1> , 
	\x<0> , 
	\y<23> , 
	\y<22> , 
	\y<21> , 
	\y<20> , 
	\y<19> , 
	\y<18> , 
	\y<17> , 
	\y<16> , 
	\y<15> , 
	\y<14> , 
	\y<13> , 
	\y<12> , 
	\y<11> , 
	\y<10> , 
	\y<9> , 
	\y<8> , 
	\y<7> , 
	\y<6> , 
	\y<5> , 
	\y<4> , 
	\y<3> , 
	\y<2> , 
	\y<1> , 
	\y<0> );
   input clock;
   input valid_in;
   input reset;
   output valid_out;
   input \x<5> ;
   input \x<4> ;
   input \x<3> ;
   input \x<2> ;
   input \x<1> ;
   input \x<0> ;
   output \y<23> ;
   output \y<22> ;
   output \y<21> ;
   output \y<20> ;
   output \y<19> ;
   output \y<18> ;
   output \y<17> ;
   output \y<16> ;
   output \y<15> ;
   output \y<14> ;
   output \y<13> ;
   output \y<12> ;
   output \y<11> ;
   output \y<10> ;
   output \y<9> ;
   output \y<8> ;
   output \y<7> ;
   output \y<6> ;
   output \y<5> ;
   output \y<4> ;
   output \y<3> ;
   output \y<2> ;
   output \y<1> ;
   output \y<0> ;

   // Internal wires
   wire FE_OFN56_N69;
   wire FE_OFN55_N61;
   wire FE_OFN54_N60;
   wire FE_OFN53_N60;
   wire FE_OFN52_N62;
   wire FE_OFN51_N62;
   wire FE_OFN50_N68;
   wire FE_OFN49_N68;
   wire FE_OFN48_N67;
   wire FE_OFN47_N67;
   wire FE_OFN43_N75;
   wire FE_OFN42_N75;
   wire FE_OFN41_N74;
   wire FE_OFN40_N74;
   wire FE_OFN39_y1_2;
   wire FE_OFN38_y1_2;
   wire FE_OFN37_y1_3;
   wire FE_OFN36_y1_3;
   wire FE_DBTN1_N21;
   wire FE_DBTN1_N2;
   wire FE_DBTN0_N3;
   wire \x1<5> ;
   wire \x1<4> ;
   wire \x1<3> ;
   wire \x1<2> ;
   wire \x1<1> ;
   wire \x1<0> ;
   wire \y1<18> ;
   wire \y1<17> ;
   wire \y1<16> ;
   wire \y1<15> ;
   wire \y1<14> ;
   wire \y1<13> ;
   wire \y1<12> ;
   wire \y1<11> ;
   wire \y1<10> ;
   wire \y1<9> ;
   wire \y1<8> ;
   wire \y1<7> ;
   wire \y1<6> ;
   wire \y1<5> ;
   wire \y1<4> ;
   wire \y1<3> ;
   wire \y1<2> ;
   wire \y1<1> ;
   wire valid1;
   wire N58;
   wire N60;
   wire N61;
   wire N62;
   wire N63;
   wire N64;
   wire N65;
   wire N67;
   wire N68;
   wire N69;
   wire N70;
   wire N71;
   wire N72;
   wire N73;
   wire N74;
   wire N75;
   wire N76;
   wire N77;
   wire N78;
   wire N79;
   wire N80;
   wire N81;
   wire N82;
   wire N83;
   wire N84;
   wire \x_squared<9> ;
   wire \x_squared<8> ;
   wire \x_squared<7> ;
   wire \x_squared<6> ;
   wire \x_squared<5> ;
   wire \x_squared<4> ;
   wire \x_squared<3> ;
   wire \x_squared<11> ;
   wire \x_squared<10> ;
   wire \x_cubed<9> ;
   wire \x_cubed<8> ;
   wire \x_cubed<7> ;
   wire \x_cubed<6> ;
   wire \x_cubed<5> ;
   wire \x_cubed<4> ;
   wire \x_cubed<3> ;
   wire \x_cubed<2> ;
   wire \x_cubed<1> ;
   wire \x_cubed<17> ;
   wire \x_cubed<16> ;
   wire \x_cubed<15> ;
   wire \x_cubed<14> ;
   wire \x_cubed<13> ;
   wire \x_cubed<12> ;
   wire \x_cubed<11> ;
   wire \x_cubed<10> ;
   wire \x_cubed<0> ;
   wire N9;
   wire N8;
   wire N7;
   wire N6;
   wire N5;
   wire N44;
   wire N43;
   wire N42;
   wire N41;
   wire N40;
   wire N4;
   wire N39;
   wire N3;
   wire N2;
   wire N16;
   wire N14;
   wire N13;
   wire N12;
   wire N11;
   wire N10;
   wire \add_1_root_add_0_root_add_56_3/carry<2> ;
   wire \add_1_root_add_0_root_add_56_3/carry<3> ;
   wire \add_1_root_add_0_root_add_56_3/carry<4> ;
   wire \add_1_root_add_0_root_add_56_3/carry<5> ;
   wire \add_1_root_add_0_root_add_56_3/carry<6> ;
   wire \add_1_root_add_0_root_add_56_3/carry<7> ;
   wire \add_1_root_add_0_root_add_56_3/carry<8> ;
   wire \add_1_root_add_0_root_add_56_3/carry<9> ;
   wire \add_1_root_add_0_root_add_56_3/carry<10> ;
   wire \add_1_root_add_0_root_add_56_3/carry<11> ;
   wire \add_1_root_add_0_root_add_56_3/carry<12> ;
   wire \add_1_root_add_0_root_add_56_3/carry<13> ;
   wire \add_1_root_add_0_root_add_56_3/carry<14> ;
   wire \add_1_root_add_0_root_add_56_3/carry<15> ;
   wire \add_1_root_add_0_root_add_56_3/carry<16> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<2> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<3> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<4> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<5> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<6> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<7> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<8> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<9> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<10> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<11> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<12> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<13> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<14> ;
   wire \add_1_root_add_0_root_add_56_3/SUM<15> ;
   wire \mult_56_2/A2<11> ;
   wire \mult_56_2/CARRYB<3][0> ;
   wire \mult_56_2/CARRYB<4][0> ;
   wire \mult_56_2/CARRYB<5][0> ;
   wire \mult_56_2/CARRYB<6][0> ;
   wire \mult_56_2/CARRYB<7][0> ;
   wire \mult_56_2/CARRYB<8][0> ;
   wire \mult_56_2/CARRYB<9][0> ;
   wire \mult_56_2/CARRYB<10][0> ;
   wire \mult_56_2/CARRYB<11][0> ;
   wire \add_2_root_add_0_root_add_56_3/carry<6> ;
   wire \add_2_root_add_0_root_add_56_3/carry<5> ;
   wire \add_2_root_add_0_root_add_56_3/carry<4> ;
   wire \add_2_root_add_0_root_add_56_3/carry<3> ;
   wire n1;
   wire n2;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire SYNOPSYS_UNCONNECTED__0;
   wire SYNOPSYS_UNCONNECTED__1;
   wire SYNOPSYS_UNCONNECTED__2;

   BUFX2 FE_OFC54_N69 (.Y(FE_OFN56_N69),
	.A(N69));
   BUFX2 FE_OFC53_N61 (.Y(FE_OFN55_N61),
	.A(N61));
   INVX2 FE_OFC52_N60 (.Y(FE_OFN54_N60),
	.A(FE_OFN53_N60));
   INVX1 FE_OFC51_N60 (.Y(FE_OFN53_N60),
	.A(N60));
   INVX2 FE_OFC50_N62 (.Y(FE_OFN52_N62),
	.A(FE_OFN51_N62));
   INVX2 FE_OFC49_N62 (.Y(FE_OFN51_N62),
	.A(N62));
   INVX1 FE_OFC48_N68 (.Y(FE_OFN50_N68),
	.A(FE_OFN49_N68));
   INVXL FE_OFC47_N68 (.Y(FE_OFN49_N68),
	.A(N68));
   INVX1 FE_OFC46_N67 (.Y(FE_OFN48_N67),
	.A(FE_OFN47_N67));
   INVXL FE_OFC45_N67 (.Y(FE_OFN47_N67),
	.A(N67));
   INVX1 FE_OFC41_N75 (.Y(FE_OFN43_N75),
	.A(FE_OFN42_N75));
   INVX1 FE_OFC40_N75 (.Y(FE_OFN42_N75),
	.A(N75));
   INVX1 FE_OFC39_N74 (.Y(FE_OFN41_N74),
	.A(FE_OFN40_N74));
   INVXL FE_OFC38_N74 (.Y(FE_OFN40_N74),
	.A(N74));
   INVX1 FE_OFC37_y1_2 (.Y(FE_OFN39_y1_2),
	.A(FE_OFN38_y1_2));
   INVX1 FE_OFC36_y1_2 (.Y(FE_OFN38_y1_2),
	.A(\y1<2> ));
   INVX1 FE_OFC35_y1_3 (.Y(FE_OFN37_y1_3),
	.A(FE_OFN36_y1_3));
   INVX1 FE_OFC34_y1_3 (.Y(FE_OFN36_y1_3),
	.A(\y1<3> ));
   INVX3 FE_DBTC1_N2 (.Y(FE_DBTN1_N2),
	.A(\x1<0> ));
   INVX1 FE_DBTC0_N3 (.Y(FE_DBTN0_N3),
	.A(N3));
   polynomial_a3_b2_c9_d1_in_bits6_out_bits24_DW02_mult_2 mult_54 (.\A<5> (\x1<5> ),
	.\A<4> (\x1<4> ),
	.\A<3> (\x1<3> ),
	.\A<2> (\x1<2> ),
	.\A<1> (\x1<1> ),
	.\A<0> (\x1<0> ),
	.\B<5> (\x1<5> ),
	.\B<4> (\x1<4> ),
	.\B<3> (\x1<3> ),
	.\B<2> (\x1<2> ),
	.\B<1> (\x1<1> ),
	.\B<0> (\x1<0> ),
	.TC(n1),
	.\PRODUCT<11> (\x_squared<11> ),
	.\PRODUCT<10> (\x_squared<10> ),
	.\PRODUCT<9> (\x_squared<9> ),
	.\PRODUCT<8> (\x_squared<8> ),
	.\PRODUCT<7> (\x_squared<7> ),
	.\PRODUCT<6> (\x_squared<6> ),
	.\PRODUCT<5> (\x_squared<5> ),
	.\PRODUCT<4> (\x_squared<4> ),
	.\PRODUCT<3> (\x_squared<3> ),
	.\PRODUCT<2> (N4),
	.\PRODUCT<1> (N3),
	.\PRODUCT<0> (N2),
	.p1(FE_DBTN1_N21),
	.p2(FE_DBTN1_N2));
   polynomial_a3_b2_c9_d1_in_bits6_out_bits24_DW02_mult_0 mult_55 (.\A<11> (\x_squared<11> ),
	.\A<10> (\x_squared<10> ),
	.\A<9> (\x_squared<9> ),
	.\A<8> (\x_squared<8> ),
	.\A<7> (\x_squared<7> ),
	.\A<6> (\x_squared<6> ),
	.\A<5> (\x_squared<5> ),
	.\A<4> (\x_squared<4> ),
	.\A<3> (\x_squared<3> ),
	.\A<2> (N4),
	.\A<1> (FE_DBTN0_N3),
	.\A<0> (FE_DBTN1_N2),
	.\B<5> (\x1<5> ),
	.\B<4> (\x1<4> ),
	.\B<3> (\x1<3> ),
	.\B<2> (\x1<2> ),
	.\B<1> (\x1<1> ),
	.\B<0> (\x1<0> ),
	.TC(n1),
	.\PRODUCT<17> (\x_cubed<17> ),
	.\PRODUCT<16> (\x_cubed<16> ),
	.\PRODUCT<15> (\x_cubed<15> ),
	.\PRODUCT<14> (\x_cubed<14> ),
	.\PRODUCT<13> (\x_cubed<13> ),
	.\PRODUCT<12> (\x_cubed<12> ),
	.\PRODUCT<11> (\x_cubed<11> ),
	.\PRODUCT<10> (\x_cubed<10> ),
	.\PRODUCT<9> (\x_cubed<9> ),
	.\PRODUCT<8> (\x_cubed<8> ),
	.\PRODUCT<7> (\x_cubed<7> ),
	.\PRODUCT<6> (\x_cubed<6> ),
	.\PRODUCT<5> (\x_cubed<5> ),
	.\PRODUCT<4> (\x_cubed<4> ),
	.\PRODUCT<3> (\x_cubed<3> ),
	.\PRODUCT<2> (\x_cubed<2> ),
	.\PRODUCT<1> (\x_cubed<1> ),
	.\PRODUCT<0> (\x_cubed<0> ));
   polynomial_a3_b2_c9_d1_in_bits6_out_bits24_DW01_add_0 add_0_root_add_0_root_add_56_3 (.\A<20> (n1),
	.\A<19> (n1),
	.\A<18> (n1),
	.\A<17> (\x_cubed<17> ),
	.\A<16> (\x_cubed<16> ),
	.\A<15> (\x_cubed<15> ),
	.\A<14> (\x_cubed<14> ),
	.\A<13> (\x_cubed<13> ),
	.\A<12> (\x_cubed<12> ),
	.\A<11> (\x_cubed<11> ),
	.\A<10> (\x_cubed<10> ),
	.\A<9> (\x_cubed<9> ),
	.\A<8> (\x_cubed<8> ),
	.\A<7> (\x_cubed<7> ),
	.\A<6> (\x_cubed<6> ),
	.\A<5> (\x_cubed<5> ),
	.\A<4> (\x_cubed<4> ),
	.\A<3> (\x_cubed<3> ),
	.\A<2> (\x_cubed<2> ),
	.\A<1> (\x_cubed<1> ),
	.\A<0> (\x_cubed<0> ),
	.\B<20> (n1),
	.\B<19> (n1),
	.\B<18> (n1),
	.\B<17> (n1),
	.\B<16> (\add_1_root_add_0_root_add_56_3/carry<16> ),
	.\B<15> (\add_1_root_add_0_root_add_56_3/SUM<15> ),
	.\B<14> (\add_1_root_add_0_root_add_56_3/SUM<14> ),
	.\B<13> (\add_1_root_add_0_root_add_56_3/SUM<13> ),
	.\B<12> (\add_1_root_add_0_root_add_56_3/SUM<12> ),
	.\B<11> (\add_1_root_add_0_root_add_56_3/SUM<11> ),
	.\B<10> (\add_1_root_add_0_root_add_56_3/SUM<10> ),
	.\B<9> (\add_1_root_add_0_root_add_56_3/SUM<9> ),
	.\B<8> (\add_1_root_add_0_root_add_56_3/SUM<8> ),
	.\B<7> (\add_1_root_add_0_root_add_56_3/SUM<7> ),
	.\B<6> (\add_1_root_add_0_root_add_56_3/SUM<6> ),
	.\B<5> (\add_1_root_add_0_root_add_56_3/SUM<5> ),
	.\B<4> (\add_1_root_add_0_root_add_56_3/SUM<4> ),
	.\B<3> (\add_1_root_add_0_root_add_56_3/SUM<3> ),
	.\B<2> (\add_1_root_add_0_root_add_56_3/SUM<2> ),
	.\B<1> (FE_DBTN0_N3),
	.\B<0> (n8),
	.CI(n1),
	.\SUM<20> (SYNOPSYS_UNCONNECTED__0),
	.\SUM<19> (SYNOPSYS_UNCONNECTED__1),
	.\SUM<18> (\y1<18> ),
	.\SUM<17> (\y1<17> ),
	.\SUM<16> (\y1<16> ),
	.\SUM<15> (\y1<15> ),
	.\SUM<14> (\y1<14> ),
	.\SUM<13> (\y1<13> ),
	.\SUM<12> (\y1<12> ),
	.\SUM<11> (\y1<11> ),
	.\SUM<10> (\y1<10> ),
	.\SUM<9> (\y1<9> ),
	.\SUM<8> (\y1<8> ),
	.\SUM<7> (\y1<7> ),
	.\SUM<6> (\y1<6> ),
	.\SUM<5> (\y1<5> ),
	.\SUM<4> (\y1<4> ),
	.\SUM<3> (\y1<3> ),
	.\SUM<2> (\y1<2> ),
	.\SUM<1> (\y1<1> ),
	.\SUM<0> (SYNOPSYS_UNCONNECTED__2),
	.N3(N3));
   DFFHQX1 \y_reg<18>  (.Q(\y<18> ),
	.D(N84),
	.CK(clock));
   DFFHQX1 \y_reg<17>  (.Q(\y<17> ),
	.D(N83),
	.CK(clock));
   DFFHQX1 \y_reg<16>  (.Q(\y<16> ),
	.D(N82),
	.CK(clock));
   DFFHQX1 \y_reg<15>  (.Q(\y<15> ),
	.D(N81),
	.CK(clock));
   DFFHQX1 \y_reg<14>  (.Q(\y<14> ),
	.D(N80),
	.CK(clock));
   DFFHQX1 \y_reg<13>  (.Q(\y<13> ),
	.D(N79),
	.CK(clock));
   DFFHQX1 \y_reg<12>  (.Q(\y<12> ),
	.D(N78),
	.CK(clock));
   DFFHQX1 \y_reg<11>  (.Q(\y<11> ),
	.D(N77),
	.CK(clock));
   DFFHQX1 \y_reg<10>  (.Q(\y<10> ),
	.D(N76),
	.CK(clock));
   DFFHQX1 \y_reg<9>  (.Q(\y<9> ),
	.D(FE_OFN43_N75),
	.CK(clock));
   DFFHQX1 \y_reg<8>  (.Q(\y<8> ),
	.D(FE_OFN41_N74),
	.CK(clock));
   DFFHQX1 \y_reg<7>  (.Q(\y<7> ),
	.D(N73),
	.CK(clock));
   DFFHQX1 \y_reg<6>  (.Q(\y<6> ),
	.D(N72),
	.CK(clock));
   DFFHQX1 \y_reg<5>  (.Q(\y<5> ),
	.D(N71),
	.CK(clock));
   DFFHQX1 \y_reg<4>  (.Q(\y<4> ),
	.D(N70),
	.CK(clock));
   DFFHQX1 \y_reg<3>  (.Q(\y<3> ),
	.D(FE_OFN56_N69),
	.CK(clock));
   DFFHQX1 \y_reg<2>  (.Q(\y<2> ),
	.D(FE_OFN50_N68),
	.CK(clock));
   DFFHQX1 \y_reg<1>  (.Q(\y<1> ),
	.D(FE_OFN48_N67),
	.CK(clock));
   DFFHQX1 \y_reg<0>  (.Q(\y<0> ),
	.D(n4),
	.CK(clock));
   DFFHQX1 valid1_reg (.Q(valid1),
	.D(N58),
	.CK(clock));
   DFFHQX1 \x1_reg<4>  (.Q(\x1<4> ),
	.D(N64),
	.CK(clock));
   DFFHQX1 \x1_reg<3>  (.Q(\x1<3> ),
	.D(N63),
	.CK(clock));
   DFFHQX1 \x1_reg<2>  (.Q(\x1<2> ),
	.D(FE_OFN52_N62),
	.CK(clock));
   DFFHQX1 \x1_reg<1>  (.Q(\x1<1> ),
	.D(FE_OFN55_N61),
	.CK(clock));
   DFFHQX1 \x1_reg<5>  (.Q(\x1<5> ),
	.D(N65),
	.CK(clock));
   DFFHQX1 \x1_reg<0>  (.Q(\x1<0> ),
	.D(FE_OFN54_N60),
	.CK(clock));
   MDFFHQX1 valid_out_reg (.Q(valid_out),
	.D0(n1),
	.D1(n4),
	.S0(valid1),
	.CK(clock));
   TIELO U3 (.Y(n1));
   INVX1 U5 (.Y(n4),
	.A(reset));
   INVX1 U6 (.Y(n5),
	.A(n7));
   AND2X1 U7 (.Y(n2),
	.A(n6),
	.B(n7));
   ADDFX1 U8 (.CO(\mult_56_2/CARRYB<10][0> ),
	.S(N12),
	.A(\x_squared<10> ),
	.B(\mult_56_2/CARRYB<9][0> ),
	.CI(\x_squared<7> ));
   ADDFX1 U9 (.CO(\mult_56_2/CARRYB<9][0> ),
	.S(N11),
	.A(\x_squared<9> ),
	.B(\mult_56_2/CARRYB<8][0> ),
	.CI(\x_squared<6> ));
   ADDFX1 U11 (.CO(\mult_56_2/CARRYB<7][0> ),
	.S(N9),
	.A(\x_squared<7> ),
	.B(\mult_56_2/CARRYB<6][0> ),
	.CI(\x_squared<4> ));
   ADDFX1 U12 (.CO(\mult_56_2/CARRYB<8][0> ),
	.S(N10),
	.A(\x_squared<8> ),
	.B(\mult_56_2/CARRYB<7][0> ),
	.CI(\x_squared<5> ));
   ADDFX1 U13 (.CO(\mult_56_2/CARRYB<6][0> ),
	.S(N8),
	.A(\x_squared<6> ),
	.B(\mult_56_2/CARRYB<5][0> ),
	.CI(\x_squared<3> ));
   ADDFX1 U14 (.CO(\mult_56_2/CARRYB<11][0> ),
	.S(N13),
	.A(\x_squared<11> ),
	.B(\mult_56_2/CARRYB<10][0> ),
	.CI(\x_squared<8> ));
   NOR2BX1 U15 (.Y(N79),
	.AN(\y1<13> ),
	.B(reset));
   NOR2BX1 U16 (.Y(N80),
	.AN(\y1<14> ),
	.B(reset));
   NOR2BX1 U17 (.Y(N81),
	.AN(\y1<15> ),
	.B(reset));
   NOR2BX1 U18 (.Y(N82),
	.AN(\y1<16> ),
	.B(reset));
   NOR2BX1 U19 (.Y(N83),
	.AN(\y1<17> ),
	.B(reset));
   NOR2BX1 U20 (.Y(N84),
	.AN(\y1<18> ),
	.B(reset));
   CLKXOR2X1 U21 (.Y(N16),
	.A(n5),
	.B(\x_squared<11> ));
   NOR2BX1 U22 (.Y(N75),
	.AN(\y1<9> ),
	.B(reset));
   NOR2BX1 U23 (.Y(N76),
	.AN(\y1<10> ),
	.B(reset));
   NOR2BX1 U24 (.Y(N77),
	.AN(\y1<11> ),
	.B(reset));
   NOR2BX1 U25 (.Y(N78),
	.AN(\y1<12> ),
	.B(reset));
   AND2X1 U26 (.Y(n3),
	.A(n5),
	.B(\x_squared<11> ));
   NOR2BX2 U27 (.Y(N71),
	.AN(\y1<5> ),
	.B(reset));
   NOR2BX1 U28 (.Y(N72),
	.AN(\y1<6> ),
	.B(reset));
   NOR2BX1 U29 (.Y(N73),
	.AN(\y1<7> ),
	.B(reset));
   NOR2BX1 U30 (.Y(N74),
	.AN(\y1<8> ),
	.B(reset));
   NOR2BX1 U31 (.Y(N68),
	.AN(FE_OFN39_y1_2),
	.B(reset));
   NOR2BX1 U32 (.Y(N69),
	.AN(FE_OFN37_y1_3),
	.B(reset));
   NOR2BX2 U33 (.Y(N70),
	.AN(\y1<4> ),
	.B(reset));
   NOR2BX1 U34 (.Y(N67),
	.AN(\y1<1> ),
	.B(reset));
   ADDFX1 U35 (.CO(\mult_56_2/CARRYB<5][0> ),
	.S(N7),
	.A(\x_squared<5> ),
	.B(\mult_56_2/CARRYB<4][0> ),
	.CI(N4));
   ADDFX1 U36 (.CO(\add_1_root_add_0_root_add_56_3/carry<4> ),
	.S(\add_1_root_add_0_root_add_56_3/SUM<3> ),
	.A(N5),
	.B(N40),
	.CI(\add_1_root_add_0_root_add_56_3/carry<3> ));
   ADDFX1 U37 (.CO(\add_1_root_add_0_root_add_56_3/carry<5> ),
	.S(\add_1_root_add_0_root_add_56_3/SUM<4> ),
	.A(N6),
	.B(N41),
	.CI(\add_1_root_add_0_root_add_56_3/carry<4> ));
   ADDFX1 U38 (.CO(\add_1_root_add_0_root_add_56_3/carry<6> ),
	.S(\add_1_root_add_0_root_add_56_3/SUM<5> ),
	.A(N7),
	.B(N42),
	.CI(\add_1_root_add_0_root_add_56_3/carry<5> ));
   ADDFX1 U39 (.CO(\add_1_root_add_0_root_add_56_3/carry<7> ),
	.S(\add_1_root_add_0_root_add_56_3/SUM<6> ),
	.A(N8),
	.B(N43),
	.CI(\add_1_root_add_0_root_add_56_3/carry<6> ));
   ADDFX1 U40 (.CO(\add_1_root_add_0_root_add_56_3/carry<8> ),
	.S(\add_1_root_add_0_root_add_56_3/SUM<7> ),
	.A(N9),
	.B(N44),
	.CI(\add_1_root_add_0_root_add_56_3/carry<7> ));
   ADDFX1 U41 (.CO(\mult_56_2/CARRYB<4][0> ),
	.S(N6),
	.A(\x_squared<4> ),
	.B(\mult_56_2/CARRYB<3][0> ),
	.CI(N3));
   ADDFX1 U42 (.CO(\add_1_root_add_0_root_add_56_3/carry<3> ),
	.S(\add_1_root_add_0_root_add_56_3/SUM<2> ),
	.A(N4),
	.B(N39),
	.CI(\add_1_root_add_0_root_add_56_3/carry<2> ));
   ADDFX1 U43 (.CO(\add_1_root_add_0_root_add_56_3/carry<2> ),
	.A(N3),
	.B(FE_DBTN1_N2),
	.CI(N2));
   NOR2BX1 U45 (.Y(N60),
	.AN(\x<0> ),
	.B(reset));
   NOR2BX1 U46 (.Y(N61),
	.AN(\x<1> ),
	.B(reset));
   NOR2BX1 U47 (.Y(N62),
	.AN(\x<2> ),
	.B(reset));
   NOR2BX1 U48 (.Y(N63),
	.AN(\x<3> ),
	.B(reset));
   NOR2BX1 U49 (.Y(N64),
	.AN(\x<4> ),
	.B(reset));
   NOR2BX1 U50 (.Y(N65),
	.AN(\x<5> ),
	.B(reset));
   NOR2BX1 U51 (.Y(N58),
	.AN(valid_in),
	.B(reset));
   AND2X1 U52 (.Y(\add_1_root_add_0_root_add_56_3/carry<16> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<15> ),
	.B(n3));
   CLKXOR2X1 U53 (.Y(\add_1_root_add_0_root_add_56_3/SUM<15> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<15> ),
	.B(n3));
   AND2X1 U54 (.Y(\add_1_root_add_0_root_add_56_3/carry<15> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<14> ),
	.B(N16));
   CLKXOR2X1 U55 (.Y(\add_1_root_add_0_root_add_56_3/SUM<14> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<14> ),
	.B(N16));
   AND2X1 U56 (.Y(\add_1_root_add_0_root_add_56_3/carry<14> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<13> ),
	.B(n2));
   CLKXOR2X1 U57 (.Y(\add_1_root_add_0_root_add_56_3/SUM<13> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<13> ),
	.B(n2));
   AND2X1 U58 (.Y(\add_1_root_add_0_root_add_56_3/carry<13> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<12> ),
	.B(N14));
   CLKXOR2X1 U59 (.Y(\add_1_root_add_0_root_add_56_3/SUM<12> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<12> ),
	.B(N14));
   AND2X1 U60 (.Y(\add_1_root_add_0_root_add_56_3/carry<12> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<11> ),
	.B(N13));
   CLKXOR2X1 U61 (.Y(\add_1_root_add_0_root_add_56_3/SUM<11> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<11> ),
	.B(N13));
   AND2X1 U62 (.Y(\add_1_root_add_0_root_add_56_3/carry<11> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<10> ),
	.B(N12));
   CLKXOR2X1 U63 (.Y(\add_1_root_add_0_root_add_56_3/SUM<10> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<10> ),
	.B(N12));
   AND2X1 U64 (.Y(\add_1_root_add_0_root_add_56_3/carry<10> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<9> ),
	.B(N11));
   CLKXOR2X1 U65 (.Y(\add_1_root_add_0_root_add_56_3/SUM<9> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<9> ),
	.B(N11));
   AND2X1 U66 (.Y(\add_1_root_add_0_root_add_56_3/carry<9> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<8> ),
	.B(N10));
   CLKXOR2X1 U67 (.Y(\add_1_root_add_0_root_add_56_3/SUM<8> ),
	.A(\add_1_root_add_0_root_add_56_3/carry<8> ),
	.B(N10));
   AND2X1 U68 (.Y(N44),
	.A(\add_2_root_add_0_root_add_56_3/carry<6> ),
	.B(\x1<5> ));
   CLKXOR2X1 U69 (.Y(N43),
	.A(\add_2_root_add_0_root_add_56_3/carry<6> ),
	.B(\x1<5> ));
   AND2X1 U70 (.Y(\add_2_root_add_0_root_add_56_3/carry<6> ),
	.A(\add_2_root_add_0_root_add_56_3/carry<5> ),
	.B(\x1<4> ));
   CLKXOR2X1 U71 (.Y(N42),
	.A(\add_2_root_add_0_root_add_56_3/carry<5> ),
	.B(\x1<4> ));
   AND2X1 U72 (.Y(\add_2_root_add_0_root_add_56_3/carry<5> ),
	.A(\add_2_root_add_0_root_add_56_3/carry<4> ),
	.B(\x1<3> ));
   CLKXOR2X1 U73 (.Y(N41),
	.A(\add_2_root_add_0_root_add_56_3/carry<4> ),
	.B(\x1<3> ));
   AND2X1 U74 (.Y(\add_2_root_add_0_root_add_56_3/carry<4> ),
	.A(\add_2_root_add_0_root_add_56_3/carry<3> ),
	.B(\x1<2> ));
   CLKXOR2X1 U75 (.Y(N40),
	.A(\add_2_root_add_0_root_add_56_3/carry<3> ),
	.B(\x1<2> ));
   AND2X1 U76 (.Y(\add_2_root_add_0_root_add_56_3/carry<3> ),
	.A(\x1<0> ),
	.B(\x1<1> ));
   CLKXOR2X1 U77 (.Y(N39),
	.A(\x1<0> ),
	.B(\x1<1> ));
   AND2X1 U78 (.Y(\mult_56_2/A2<11> ),
	.A(\x_squared<9> ),
	.B(\mult_56_2/CARRYB<11][0> ));
   CLKXOR2X1 U79 (.Y(N14),
	.A(\x_squared<9> ),
	.B(\mult_56_2/CARRYB<11][0> ));
   AND2X1 U80 (.Y(\mult_56_2/CARRYB<3][0> ),
	.A(N2),
	.B(\x_squared<3> ));
   CLKXOR2X1 U81 (.Y(N5),
	.A(N2),
	.B(\x_squared<3> ));
   NAND2X1 U82 (.Y(n7),
	.A(\mult_56_2/A2<11> ),
	.B(\x_squared<10> ));
   OR2X1 U83 (.Y(n6),
	.A(\mult_56_2/A2<11> ),
	.B(\x_squared<10> ));
endmodule

module polynomial_top (
	PAD_clock, 
	PAD_valid_in, 
	PAD_reset, 
	PAD_valid_out, 
	\PAD_x<5> , 
	\PAD_x<4> , 
	\PAD_x<3> , 
	\PAD_x<2> , 
	\PAD_x<1> , 
	\PAD_x<0> , 
	\PAD_y<23> , 
	\PAD_y<22> , 
	\PAD_y<21> , 
	\PAD_y<20> , 
	\PAD_y<19> , 
	\PAD_y<18> , 
	\PAD_y<17> , 
	\PAD_y<16> , 
	\PAD_y<15> , 
	\PAD_y<14> , 
	\PAD_y<13> , 
	\PAD_y<12> , 
	\PAD_y<11> , 
	\PAD_y<10> , 
	\PAD_y<9> , 
	\PAD_y<8> , 
	\PAD_y<7> , 
	\PAD_y<6> , 
	\PAD_y<5> , 
	\PAD_y<4> , 
	\PAD_y<3> , 
	\PAD_y<2> , 
	\PAD_y<1> , 
	\PAD_y<0> );
   input PAD_clock;
   input PAD_valid_in;
   input PAD_reset;
   output PAD_valid_out;
   input \PAD_x<5> ;
   input \PAD_x<4> ;
   input \PAD_x<3> ;
   input \PAD_x<2> ;
   input \PAD_x<1> ;
   input \PAD_x<0> ;
   output \PAD_y<23> ;
   output \PAD_y<22> ;
   output \PAD_y<21> ;
   output \PAD_y<20> ;
   output \PAD_y<19> ;
   output \PAD_y<18> ;
   output \PAD_y<17> ;
   output \PAD_y<16> ;
   output \PAD_y<15> ;
   output \PAD_y<14> ;
   output \PAD_y<13> ;
   output \PAD_y<12> ;
   output \PAD_y<11> ;
   output \PAD_y<10> ;
   output \PAD_y<9> ;
   output \PAD_y<8> ;
   output \PAD_y<7> ;
   output \PAD_y<6> ;
   output \PAD_y<5> ;
   output \PAD_y<4> ;
   output \PAD_y<3> ;
   output \PAD_y<2> ;
   output \PAD_y<1> ;
   output \PAD_y<0> ;

   // Internal wires
   wire FE_OFN35_valid_out_top;
   wire FE_OFN34_valid_out_top;
   wire FE_OFN33_y_top_1;
   wire FE_OFN32_y_top_1;
   wire FE_OFN31_y_top_2;
   wire FE_OFN30_y_top_2;
   wire FE_OFN29_y_top_3;
   wire FE_OFN28_y_top_3;
   wire FE_OFN27_y_top_4;
   wire FE_OFN26_y_top_4;
   wire FE_OFN25_y_top_7;
   wire FE_OFN24_y_top_7;
   wire FE_OFN23_y_top_8;
   wire FE_OFN22_y_top_8;
   wire FE_OFN21_y_top_9;
   wire FE_OFN20_y_top_9;
   wire FE_OFN19_y_top_10;
   wire FE_OFN18_y_top_10;
   wire FE_OFN17_y_top_11;
   wire FE_OFN16_y_top_11;
   wire FE_OFN15_y_top_12;
   wire FE_OFN14_y_top_12;
   wire FE_OFN13_y_top_13;
   wire FE_OFN12_y_top_13;
   wire FE_OFN11_y_top_14;
   wire FE_OFN10_y_top_14;
   wire FE_OFN9_y_top_15;
   wire FE_OFN8_y_top_15;
   wire FE_OFN7_y_top_16;
   wire FE_OFN6_y_top_16;
   wire FE_OFN5_y_top_17;
   wire FE_OFN4_y_top_17;
   wire FE_OFN3_y_top_18;
   wire FE_OFN2_y_top_18;
   wire \x_top<5> ;
   wire \x_top<4> ;
   wire \x_top<3> ;
   wire \x_top<2> ;
   wire \x_top<1> ;
   wire \x_top<0> ;
   wire \y_top<18> ;
   wire \y_top<17> ;
   wire \y_top<16> ;
   wire \y_top<15> ;
   wire \y_top<14> ;
   wire \y_top<13> ;
   wire \y_top<12> ;
   wire \y_top<11> ;
   wire \y_top<10> ;
   wire \y_top<9> ;
   wire \y_top<8> ;
   wire \y_top<7> ;
   wire \y_top<6> ;
   wire \y_top<5> ;
   wire \y_top<4> ;
   wire \y_top<3> ;
   wire \y_top<2> ;
   wire \y_top<1> ;
   wire \y_top<0> ;
   wire clock_top;
   wire valid_in_top;
   wire reset_top;
   wire valid_out_top;
   wire n1;
   wire SYNOPSYS_UNCONNECTED__0;
   wire SYNOPSYS_UNCONNECTED__1;
   wire SYNOPSYS_UNCONNECTED__2;
   wire SYNOPSYS_UNCONNECTED__3;
   wire SYNOPSYS_UNCONNECTED__4;

   INVX2 FE_OFC33_valid_out_top (.Y(FE_OFN35_valid_out_top),
	.A(FE_OFN34_valid_out_top));
   INVX1 FE_OFC32_valid_out_top (.Y(FE_OFN34_valid_out_top),
	.A(valid_out_top));
   INVX1 FE_OFC31_y_top_1 (.Y(FE_OFN33_y_top_1),
	.A(FE_OFN32_y_top_1));
   INVX1 FE_OFC30_y_top_1 (.Y(FE_OFN32_y_top_1),
	.A(\y_top<1> ));
   INVX1 FE_OFC29_y_top_2 (.Y(FE_OFN31_y_top_2),
	.A(FE_OFN30_y_top_2));
   INVX1 FE_OFC28_y_top_2 (.Y(FE_OFN30_y_top_2),
	.A(\y_top<2> ));
   INVX1 FE_OFC27_y_top_3 (.Y(FE_OFN29_y_top_3),
	.A(FE_OFN28_y_top_3));
   INVX1 FE_OFC26_y_top_3 (.Y(FE_OFN28_y_top_3),
	.A(\y_top<3> ));
   INVX1 FE_OFC25_y_top_4 (.Y(FE_OFN27_y_top_4),
	.A(FE_OFN26_y_top_4));
   INVX1 FE_OFC24_y_top_4 (.Y(FE_OFN26_y_top_4),
	.A(\y_top<4> ));
   INVX1 FE_OFC23_y_top_7 (.Y(FE_OFN25_y_top_7),
	.A(FE_OFN24_y_top_7));
   INVX1 FE_OFC22_y_top_7 (.Y(FE_OFN24_y_top_7),
	.A(\y_top<7> ));
   INVX1 FE_OFC21_y_top_8 (.Y(FE_OFN23_y_top_8),
	.A(FE_OFN22_y_top_8));
   INVX1 FE_OFC20_y_top_8 (.Y(FE_OFN22_y_top_8),
	.A(\y_top<8> ));
   INVX1 FE_OFC19_y_top_9 (.Y(FE_OFN21_y_top_9),
	.A(FE_OFN20_y_top_9));
   INVX1 FE_OFC18_y_top_9 (.Y(FE_OFN20_y_top_9),
	.A(\y_top<9> ));
   INVX3 FE_OFC17_y_top_10 (.Y(FE_OFN19_y_top_10),
	.A(FE_OFN18_y_top_10));
   INVX3 FE_OFC16_y_top_10 (.Y(FE_OFN18_y_top_10),
	.A(\y_top<10> ));
   INVX3 FE_OFC15_y_top_11 (.Y(FE_OFN17_y_top_11),
	.A(FE_OFN16_y_top_11));
   INVX3 FE_OFC14_y_top_11 (.Y(FE_OFN16_y_top_11),
	.A(\y_top<11> ));
   INVX2 FE_OFC13_y_top_12 (.Y(FE_OFN15_y_top_12),
	.A(FE_OFN14_y_top_12));
   INVX3 FE_OFC12_y_top_12 (.Y(FE_OFN14_y_top_12),
	.A(\y_top<12> ));
   INVX3 FE_OFC11_y_top_13 (.Y(FE_OFN13_y_top_13),
	.A(FE_OFN12_y_top_13));
   INVX1 FE_OFC10_y_top_13 (.Y(FE_OFN12_y_top_13),
	.A(\y_top<13> ));
   INVX2 FE_OFC9_y_top_14 (.Y(FE_OFN11_y_top_14),
	.A(FE_OFN10_y_top_14));
   INVX2 FE_OFC8_y_top_14 (.Y(FE_OFN10_y_top_14),
	.A(\y_top<14> ));
   INVX2 FE_OFC7_y_top_15 (.Y(FE_OFN9_y_top_15),
	.A(FE_OFN8_y_top_15));
   INVX2 FE_OFC6_y_top_15 (.Y(FE_OFN8_y_top_15),
	.A(\y_top<15> ));
   INVX2 FE_OFC5_y_top_16 (.Y(FE_OFN7_y_top_16),
	.A(FE_OFN6_y_top_16));
   INVX1 FE_OFC4_y_top_16 (.Y(FE_OFN6_y_top_16),
	.A(\y_top<16> ));
   INVX2 FE_OFC3_y_top_17 (.Y(FE_OFN5_y_top_17),
	.A(FE_OFN4_y_top_17));
   INVX2 FE_OFC2_y_top_17 (.Y(FE_OFN4_y_top_17),
	.A(\y_top<17> ));
   INVX2 FE_OFC1_y_top_18 (.Y(FE_OFN3_y_top_18),
	.A(FE_OFN2_y_top_18));
   INVX2 FE_OFC0_y_top_18 (.Y(FE_OFN2_y_top_18),
	.A(\y_top<18> ));
   PADDI inpX_5 (.PAD(\PAD_x<5> ),
	.Y(\x_top<5> ));
   PADDI inpX_4 (.PAD(\PAD_x<4> ),
	.Y(\x_top<4> ));
   PADDI inpX_3 (.PAD(\PAD_x<3> ),
	.Y(\x_top<3> ));
   PADDI inpX_2 (.PAD(\PAD_x<2> ),
	.Y(\x_top<2> ));
   PADDI inpX_1 (.PAD(\PAD_x<1> ),
	.Y(\x_top<1> ));
   PADDI inpX_0 (.PAD(\PAD_x<0> ),
	.Y(\x_top<0> ));
   PADDO outpY_23 (.A(n1),
	.PAD(\PAD_y<23> ));
   PADDO outpY_22 (.A(n1),
	.PAD(\PAD_y<22> ));
   PADDO outpY_21 (.A(n1),
	.PAD(\PAD_y<21> ));
   PADDO outpY_20 (.A(n1),
	.PAD(\PAD_y<20> ));
   PADDO outpY_19 (.A(n1),
	.PAD(\PAD_y<19> ));
   PADDO outpY_18 (.A(FE_OFN3_y_top_18),
	.PAD(\PAD_y<18> ));
   PADDO outpY_17 (.A(FE_OFN5_y_top_17),
	.PAD(\PAD_y<17> ));
   PADDO outpY_16 (.A(FE_OFN7_y_top_16),
	.PAD(\PAD_y<16> ));
   PADDO outpY_15 (.A(FE_OFN9_y_top_15),
	.PAD(\PAD_y<15> ));
   PADDO outpY_14 (.A(FE_OFN11_y_top_14),
	.PAD(\PAD_y<14> ));
   PADDO outpY_13 (.A(FE_OFN13_y_top_13),
	.PAD(\PAD_y<13> ));
   PADDO outpY_12 (.A(FE_OFN15_y_top_12),
	.PAD(\PAD_y<12> ));
   PADDO outpY_11 (.A(FE_OFN17_y_top_11),
	.PAD(\PAD_y<11> ));
   PADDO outpY_10 (.A(FE_OFN19_y_top_10),
	.PAD(\PAD_y<10> ));
   PADDO outpY_9 (.A(FE_OFN21_y_top_9),
	.PAD(\PAD_y<9> ));
   PADDO outpY_8 (.A(FE_OFN23_y_top_8),
	.PAD(\PAD_y<8> ));
   PADDO outpY_7 (.A(FE_OFN25_y_top_7),
	.PAD(\PAD_y<7> ));
   PADDO outpY_6 (.A(\y_top<6> ),
	.PAD(\PAD_y<6> ));
   PADDO outpY_5 (.A(\y_top<5> ),
	.PAD(\PAD_y<5> ));
   PADDO outpY_4 (.A(FE_OFN27_y_top_4),
	.PAD(\PAD_y<4> ));
   PADDO outpY_3 (.A(FE_OFN29_y_top_3),
	.PAD(\PAD_y<3> ));
   PADDO outpY_2 (.A(FE_OFN31_y_top_2),
	.PAD(\PAD_y<2> ));
   PADDO outpY_1 (.A(FE_OFN33_y_top_1),
	.PAD(\PAD_y<1> ));
   PADDO outpY_0 (.A(\y_top<0> ),
	.PAD(\PAD_y<0> ));
   PADDI padClock (.PAD(PAD_clock),
	.Y(clock_top));
   PADDI padValidIn (.PAD(PAD_valid_in),
	.Y(valid_in_top));
   PADDI padReset (.PAD(PAD_reset),
	.Y(reset_top));
   PADDO padValidOut (.A(FE_OFN35_valid_out_top),
	.PAD(PAD_valid_out));
   polynomial_a3_b2_c9_d1_in_bits6_out_bits24 polynomialCore (.clock(clock_top),
	.valid_in(valid_in_top),
	.reset(reset_top),
	.valid_out(valid_out_top),
	.\x<5> (\x_top<5> ),
	.\x<4> (\x_top<4> ),
	.\x<3> (\x_top<3> ),
	.\x<2> (\x_top<2> ),
	.\x<1> (\x_top<1> ),
	.\x<0> (\x_top<0> ),
	.\y<23> (SYNOPSYS_UNCONNECTED__0),
	.\y<22> (SYNOPSYS_UNCONNECTED__1),
	.\y<21> (SYNOPSYS_UNCONNECTED__2),
	.\y<20> (SYNOPSYS_UNCONNECTED__3),
	.\y<19> (SYNOPSYS_UNCONNECTED__4),
	.\y<18> (\y_top<18> ),
	.\y<17> (\y_top<17> ),
	.\y<16> (\y_top<16> ),
	.\y<15> (\y_top<15> ),
	.\y<14> (\y_top<14> ),
	.\y<13> (\y_top<13> ),
	.\y<12> (\y_top<12> ),
	.\y<11> (\y_top<11> ),
	.\y<10> (\y_top<10> ),
	.\y<9> (\y_top<9> ),
	.\y<8> (\y_top<8> ),
	.\y<7> (\y_top<7> ),
	.\y<6> (\y_top<6> ),
	.\y<5> (\y_top<5> ),
	.\y<4> (\y_top<4> ),
	.\y<3> (\y_top<3> ),
	.\y<2> (\y_top<2> ),
	.\y<1> (\y_top<1> ),
	.\y<0> (\y_top<0> ));
   TIELO U1 (.Y(n1));
endmodule

